// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace  FeishuNetSdk.FeishuEvent.V2.Task.Task.Comment
{
    /// <summary>
    /// 任务评论信息变更<br/>
    /// 当 APP 创建的任务评论信息发生变更时触发此事件，包括任务评论的创建、回复、更新、删除。<br/>
    /// </summary>
    /// <事件类型> task.task.comment.updated_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task-comment/events/updated">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 查看、创建、修改和删除任务评论 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class UpdatedV1 : EventContext<UpdatedV1.EventData>
    {
        // EventData|task_id:string||comment_id:string||parent_id:string||obj_type:int|
        public class EventData
        {
            	
            /// <summary>
            /// 任务ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("task_id")]
            public string TaskId { get; init; }

            	
            /// <summary>
            /// 任务评论ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("comment_id")]
            public string CommentId { get; init; }

            	
            /// <summary>
            /// 任务评论父ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("parent_id")]
            public string ParentId { get; init; }

            	
            /// <summary>
            /// 通知类型（1：创建评论，2：回复评论，3：更新评论，4：删除评论）
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("obj_type")]
            public int ObjType { get; init; }
        }
    }
}