// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Vc.ReserveConfig
{
    /// <summary>
    /// 更新会议室预定限制<br/>
    /// 当更新会议室预定限制时，会触发该事件。<br/>
    /// </summary>
    /// <事件类型> vc.reserve_config.updated_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/reserve_config/events/updated">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 更新视频会议室信息 </li>
    /// <li> 获取视频会议室信息 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// <ul>
    /// <li> 获取用户 user ID (仅自建应用) </li>
    /// </ul>
    /// </字段权限要求>
    public class UpdatedV1 : EventContext<UpdatedV1.EventData>
    {
        // EventData|scope_id:string||scope_type:int||approve_config:approval_config_event|approval_switch:int||approval_condition:int||meeting_duration:float||approvers:subscribe_user_event|user_id:user_id|union_id:string||user_id:string||open_id:string||time_config:time_config|time_switch:int||days_in_advance:int||opening_hour:string||start_time:string||end_time:string||max_duration:int||reserve_scope_config:reserve_scope_config_event|allow_all_users:int||allow_users:subscribe_user_event|user_id:user_id|union_id:string||user_id:string||open_id:string||allow_depts:subscribe_department|department_id:string|
        public class EventData
        {
            	
            /// <summary>
            /// 会议室或层级id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("scope_id")]
            public string ScopeId { get; init; }

            	
            /// <summary>
            /// 1代表层级，2代表会议室
            /// 数据校验规则：
            /// 取值范围：1 ～ 2
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("scope_type")]
            public int ScopeType { get; init; }

            	
            /// <summary>
            /// 预定审批设置
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("approve_config")]
            public ApprovalConfigEvent ApproveConfig { get; init; }

            	
            /// <summary>
            /// 预定时间设置
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("time_config")]
            public TimeConfig TimeConfig { get; init; }

            	
            /// <summary>
            /// 预定范围设置
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("reserve_scope_config")]
            public ReserveScopeConfigEvent ReserveScopeConfig { get; init; }
        }

        // approval_config_event|approval_switch:int||approval_condition:int||meeting_duration:float||approvers:subscribe_user_event|user_id:user_id|union_id:string||user_id:string||open_id:string|
        public class ApprovalConfigEvent
        {
            	
            /// <summary>
            /// 预定审批开关，0关闭，1打开
            /// 数据校验规则：
            /// 取值范围：0 ～ 1
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("approval_switch")]
            public int ApprovalSwitch { get; init; }

            	
            /// <summary>
            /// 预定审批条件，0所有预定需要审批，1满足条件需审批
            /// 数据校验规则：
            /// 取值范围：0 ～ 1
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("approval_condition")]
            public int ApprovalCondition { get; init; }

            	
            /// <summary>
            /// 超过 meeting_duration小时需要审批
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("meeting_duration")]
            public float MeetingDuration { get; init; }

            	
            /// <summary>
            /// 审批人列表
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("approvers")]
            public SubscribeUserEvent[] Approvers { get; init; }
        }

        // subscribe_user_event|user_id:user_id|union_id:string||user_id:string||open_id:string|
        public class SubscribeUserEvent
        {
            	
            /// <summary>
            /// 用户 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public UserId UserId { get; init; }
        }

        // user_id|union_id:string||user_id:string||open_id:string|
        public class UserId
        {
            	
            /// <summary>
            /// 用户的 union id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// 用户的 user id
            /// 字段权限要求：
            /// 获取用户 user ID仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserIdValue { get; init; }

            	
            /// <summary>
            /// 用户的 open id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }

        // time_config|time_switch:int||days_in_advance:int||opening_hour:string||start_time:string||end_time:string||max_duration:int|
        public class TimeConfig
        {
            	
            /// <summary>
            /// 预定时间开关：0 代表关闭，1 代表开启
            /// 数据校验规则：
            /// 取值范围：0 ～ 1
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("time_switch")]
            public int TimeSwitch { get; init; }

            	
            /// <summary>
            /// 最早可提前days_in_advance 预定会议室（单位：天，取值范围[1-730]）说明：不填写时，默认更新为 365
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("days_in_advance")]
            public int DaysInAdvance { get; init; }

            	
            /// <summary>
            /// 开放当天可于opening_hour 开始预定（单位：秒，取值范围[0,86400]）说明：
            /// 不填写时默认更新为28800 如果填写的值不是 60的倍数，则自动会更新为离其最近的 60 整数倍的值。
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("opening_hour")]
            public string OpeningHour { get; init; }

            	
            /// <summary>
            /// 每日可预定时间范围的开始时间（单位：秒，取值范围[0,86400]）说明：
            /// 不填写时，默认更新为 0 ，此时填写的  end_time 不得小于 30。当 start_time 与end_time 均填写时，end_time 至少超过start_time 30 。如果填写的值不是 60 的倍数，则自动会更新为离其最近的 60 整数倍的值。
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("start_time")]
            public string StartTime { get; init; }

            	
            /// <summary>
            /// 每日可预定时间范围结束时间（单位：秒，取值范围[0,86400]）说明：
            /// 不填写时，默认更新为 86400 ，此时填写的start_time 不得大于等于 86370 。当 start_time 与end_time 均填写时，end_time 至少要超过start_time 30。如果填写的值不是  60 的倍数，则自动会更新为离其最近的 60 整数倍的值。
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("end_time")]
            public string EndTime { get; init; }

            	
            /// <summary>
            /// 单次会议室可预定时长上限（单位：小时，取值范围[1,99]）说明：不填写时默认更新为 2
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("max_duration")]
            public int MaxDuration { get; init; }
        }

        // reserve_scope_config_event|allow_all_users:int||allow_users:subscribe_user_event|user_id:user_id|union_id:string||user_id:string||open_id:string||allow_depts:subscribe_department|department_id:string|
        public class ReserveScopeConfigEvent
        {
            	
            /// <summary>
            /// 可预定成员范围，0部分成员，1全部成员
            /// 数据校验规则：
            /// 取值范围：0 ～ 1
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("allow_all_users")]
            public int AllowAllUsers { get; init; }

            	
            /// <summary>
            /// 可预定成员列表
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("allow_users")]
            public SubscribeUserEvent[] AllowUsers { get; init; }

            	
            /// <summary>
            /// 可预定部门列表
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("allow_depts")]
            public SubscribeDepartment[] AllowDepts { get; init; }
        }

        // subscribe_department|department_id:string|
        public class SubscribeDepartment
        {
            	
            /// <summary>
            /// 预定管理部门ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("department_id")]
            public string DepartmentId { get; init; }
        }
    }
}