// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace  FeishuNetSdk.FeishuEvent.V2.Contact.Department
{
    /// <summary>
    /// 删除部门<br/>
    /// 订阅这一事件可以获得被删除部门的信息。<br/>
    /// </summary>
    /// <事件类型> contact.department.deleted_v3 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/contact-v3/department/events/deleted">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取通讯录基本信息 </li>
    /// <li> 以应用身份读取通讯录 </li>
    /// <li> 以应用身份访问通讯录 (历史版本) </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// <ul>
    /// <li> 获取通讯录部门组织架构信息 </li>
    /// <li> 以应用身份读取通讯录 </li>
    /// <li> 获取部门基础信息 </li>
    /// <li> 查询部门 HRBP 信息 (仅自建应用) </li>
    /// <li> 以应用身份访问通讯录 (历史版本) </li>
    /// <li> 读取通讯录 (历史版本) </li>
    /// </ul>
    /// </字段权限要求>
    public class DeletedV3 : EventContext<DeletedV3.EventData>
    {
        // EventData|object:department_event|name:string||parent_department_id:string||department_id:string||open_department_id:string||leader_user_id:string||chat_id:string||order:int||status:department_status|is_deleted:boolean||leaders:departmentLeader|leaderType:int||leaderID:string||department_hrbps:user_id|union_id:string||user_id:string||open_id:string||old_object:old_department_object|status:department_status|is_deleted:boolean||open_department_id:string|
        public class EventData
        {
            	
            /// <summary>
            /// 部门信息
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("object")]
            public DepartmentEvent Object { get; init; }

            	
            /// <summary>
            /// 部门被删除前的信息
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("old_object")]
            public OldDepartmentObject OldObject { get; init; }
        }

        // department_event|name:string||parent_department_id:string||department_id:string||open_department_id:string||leader_user_id:string||chat_id:string||order:int||status:department_status|is_deleted:boolean||leaders:departmentLeader|leaderType:int||leaderID:string||department_hrbps:user_id|union_id:string||user_id:string||open_id:string|
        public class DepartmentEvent
        {
            	
            /// <summary>
            /// 部门名称
            /// 数据校验规则：
            /// 最小长度：1 字符
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取部门基础信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("name")]
            public string Name { get; init; }

            	
            /// <summary>
            /// 父部门的部门open_department_id 部门相关ID概念
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取通讯录部门组织架构信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("parent_department_id")]
            public string ParentDepartmentId { get; init; }

            	
            /// <summary>
            /// 本部门的department_id 部门相关ID概念
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取部门基础信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("department_id")]
            public string DepartmentId { get; init; }

            	
            /// <summary>
            /// 部门的open_department_id 部门相关ID概念
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_department_id")]
            public string OpenDepartmentId { get; init; }

            	
            /// <summary>
            /// 部门主管用户open_id 用户相关的 ID 概念
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取部门基础信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("leader_user_id")]
            public string LeaderUserId { get; init; }

            	
            /// <summary>
            /// 部门群ID
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取通讯录部门组织架构信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("chat_id")]
            public string ChatId { get; init; }

            	
            /// <summary>
            /// 部门的排序
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取通讯录部门组织架构信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("order")]
            public int Order { get; init; }

            	
            /// <summary>
            /// 部门状态
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取部门基础信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("status")]
            public DepartmentStatus Status { get; init; }

            	
            /// <summary>
            /// 部门负责人
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("leaders")]
            public DepartmentLeader[] Leaders { get; init; }

            	
            /// <summary>
            /// 部门HRBP
            /// 字段权限要求：
            /// 查询部门 HRBP 信息仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("department_hrbps")]
            public UserId[] DepartmentHrbps { get; init; }
        }

        // department_status|is_deleted:boolean|
        public class DepartmentStatus
        {
            	
            /// <summary>
            /// 是否被删除
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("is_deleted")]
            public bool IsDeleted { get; init; }
        }

        // departmentLeader|leaderType:int||leaderID:string|
        public class DepartmentLeader
        {
            	
            /// <summary>
            /// 负责人类型
            /// 可选值有：
            /// 1：主负责人2：副负责人
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("leaderType")]
            public int LeaderType { get; init; }

            	
            /// <summary>
            /// 负责人ID
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取通讯录部门组织架构信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("leaderID")]
            public string LeaderID { get; init; }
        }

        // user_id|union_id:string||user_id:string||open_id:string|
        public class UserId
        {
            	
            /// <summary>
            /// Union ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// User ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserIdValue { get; init; }

            	
            /// <summary>
            /// Open ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }

        // old_department_object|status:department_status|is_deleted:boolean||open_department_id:string|
        public class OldDepartmentObject
        {
            	
            /// <summary>
            /// 部门状态
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取部门基础信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("status")]
            public DepartmentStatus Status { get; init; }

            	
            /// <summary>
            /// 部门open_id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_department_id")]
            public string OpenDepartmentId { get; init; }
        }
    }
}