// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Corehr.Offboarding
{
    /// <summary>
    /// 离职状态变更<br/>
    /// 在离职发起审批和产生审批结果时触发该事件，审批结果产生的场景包括撤销、审批通过、审批拒绝。<br/>
    /// </summary>
    /// <事件类型> corehr.offboarding.updated_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/offboarding/events/updated">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取员工离职信息 </li>
    /// <li> 获取雇佣信息 (仅自建应用) </li>
    /// <li> 更新雇佣信息 (仅自建应用) </li>
    /// <li> 读写员工离职信息 (仅自建应用) </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// <ul>
    /// <li> 获取用户 user ID (仅自建应用) </li>
    /// </ul>
    /// </字段权限要求>
    public class UpdatedV1 : EventContext<UpdatedV1.EventData>
    {
        // EventData|employment_id:string||target_user_id:user_id|union_id:string||user_id:string||open_id:string||offboarding_id:string||process_id:string||status:int|
        public class EventData
        {
            	
            /// <summary>
            /// 员工 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("employment_id")]
            public string EmploymentId { get; init; }

            	
            /// <summary>
            /// 用户 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("target_user_id")]
            public UserId TargetUserId { get; init; }

            	
            /// <summary>
            /// 离职记录 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("offboarding_id")]
            public string OffboardingId { get; init; }

            	
            /// <summary>
            /// 离职发起后的审批流程实例 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("process_id")]
            public string ProcessId { get; init; }

            	
            /// <summary>
            /// 离职状态
            /// 可选值有：
            /// 1：离职发起/审批中2：已撤销3：已拒绝4：审批通过5：已生效（生效日期后自动生效）
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("status")]
            public int Status { get; init; }
        }

        // user_id|union_id:string||user_id:string||open_id:string|
        public class UserId
        {
            	
            /// <summary>
            /// 用户的 union id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// 用户的 user id
            /// 字段权限要求：
            /// 获取用户 user ID仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserIdValue { get; init; }

            	
            /// <summary>
            /// 用户的 open id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }
    }
}