// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace  FeishuNetSdk.FeishuEvent.V2.Elearning.CourseRegistration
{
    /// <summary>
    /// 课程学习进度新增事件<br/>
    /// 课程学习进度新增时触发<br/>
    /// </summary>
    /// <事件类型> elearning.course_registration.created_v2 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/elearning-v2/course_registration/events/created">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 查看、创建、编辑、删除学员的课程学习数据 </li>
    /// <li> 获取课程学员数据 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// <ul>
    /// <li> 获取用户 user ID (仅自建应用) </li>
    /// </ul>
    /// </字段权限要求>
    public class CreatedV2 : EventContext<CreatedV2.EventCourseRegistration>
    {
        // event_course_registration|course_id:string||learner:event_user|user_id:user_id|union_id:string||user_id:string||open_id:string||email:string||phone:string||enroll_at:int||enroll_type:int||learning_duration:int||finished_at:int||learning_state:int||compulsory_lesson_ids:string||learned_compulsory_lesson_ids:string||optional_lesson_ids:string||learned_optional_lesson_ids:string|
        public class EventCourseRegistration
        {
            	
            /// <summary>
            /// 课程ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("course_id")]
            public string CourseId { get; init; }

            	
            /// <summary>
            /// 课程学员信息
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("learner")]
            public EventUser Learner { get; init; }

            	
            /// <summary>
            /// 加入学习时间戳（秒）
            /// 数据校验规则：
            /// 取值范围：0 ～ 4294967295
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("enroll_at")]
            public int EnrollAt { get; init; }

            	
            /// <summary>
            /// 注册类型
            /// 可选值有：
            /// 1：被管理员指派2：学员自主加入3：按照规则自动加入4：学员申请被批准加入
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("enroll_type")]
            public int EnrollType { get; init; }

            	
            /// <summary>
            /// 学习时长，单位：秒
            /// 数据校验规则：
            /// 取值范围：0 ～ 4294967295
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("learning_duration")]
            public int LearningDuration { get; init; }

            	
            /// <summary>
            /// 完成时间戳（秒）
            /// 数据校验规则：
            /// 取值范围：0 ～ 4294967295
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("finished_at")]
            public int FinishedAt { get; init; }

            	
            /// <summary>
            /// 完成状态
            /// 可选值有：
            /// 0：课程未开始1：课程学习中2：课程已通过3：课程不合格
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("learning_state")]
            public int LearningState { get; init; }

            	
            /// <summary>
            /// 必修章节id列表
            /// 数据校验规则：
            /// 长度范围：0 ～ 65535
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("compulsory_lesson_ids")]
            public string[] CompulsoryLessonIds { get; init; }

            	
            /// <summary>
            /// 已完成的必修章节id列表
            /// 数据校验规则：
            /// 长度范围：0 ～ 65535
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("learned_compulsory_lesson_ids")]
            public string[] LearnedCompulsoryLessonIds { get; init; }

            	
            /// <summary>
            /// 选修章节id列表
            /// 数据校验规则：
            /// 长度范围：0 ～ 65535
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("optional_lesson_ids")]
            public string[] OptionalLessonIds { get; init; }

            	
            /// <summary>
            /// 已完成的选修章节id列表
            /// 数据校验规则：
            /// 长度范围：0 ～ 65535
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("learned_optional_lesson_ids")]
            public string[] LearnedOptionalLessonIds { get; init; }
        }

        // event_user|user_id:user_id|union_id:string||user_id:string||open_id:string||email:string||phone:string|
        public class EventUser
        {
            	
            /// <summary>
            /// 用户 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public UserId UserId { get; init; }

            	
            /// <summary>
            /// 用户的 email
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("email")]
            public string Email { get; init; }

            	
            /// <summary>
            /// 用户的手机号
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("phone")]
            public string Phone { get; init; }
        }

        // user_id|union_id:string||user_id:string||open_id:string|
        public class UserId
        {
            	
            /// <summary>
            /// 用户的 union id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// 用户的 user id
            /// 字段权限要求：
            /// 获取用户 user ID仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserIdValue { get; init; }

            	
            /// <summary>
            /// 用户的 open id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }
    }
}