// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace  FeishuNetSdk.FeishuEvent.V2.Elearning.CourseRegistration
{
    /// <summary>
    /// 课程学习进度删除事件<br/>
    /// 课程学习进度删除时触发<br/>
    /// </summary>
    /// <事件类型> elearning.course_registration.deleted_v2 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/elearning-v2/course_registration/events/deleted">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 查看、创建、编辑、删除学员的课程学习数据 </li>
    /// <li> 获取课程学员数据 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// <ul>
    /// <li> 获取用户 user ID (仅自建应用) </li>
    /// </ul>
    /// </字段权限要求>
    public class DeletedV2 : EventContext<DeletedV2.EventData>
    {
        // EventData|course_id:string||learner:event_user|user_id:user_id|union_id:string||user_id:string||open_id:string||email:string||phone:string|
        public class EventData
        {
            	
            /// <summary>
            /// 课程ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("course_id")]
            public string CourseId { get; init; }

            	
            /// <summary>
            /// 课程学员信息
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("learner")]
            public EventUser Learner { get; init; }
        }

        // event_user|user_id:user_id|union_id:string||user_id:string||open_id:string||email:string||phone:string|
        public class EventUser
        {
            	
            /// <summary>
            /// 用户 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public UserId UserId { get; init; }

            	
            /// <summary>
            /// 用户的 email
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("email")]
            public string Email { get; init; }

            	
            /// <summary>
            /// 用户的手机号
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("phone")]
            public string Phone { get; init; }
        }

        // user_id|union_id:string||user_id:string||open_id:string|
        public class UserId
        {
            	
            /// <summary>
            /// 用户的 union id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// 用户的 user id
            /// 字段权限要求：
            /// 获取用户 user ID仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserIdValue { get; init; }

            	
            /// <summary>
            /// 用户的 open id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }
    }
}