// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace  FeishuNetSdk.FeishuEvent.V2.Application.Application.AppVersion
{
    /// <summary>
    /// 应用审核<br/>
    /// 通过订阅该事件，可接收应用审核（通过 / 拒绝）事件<br/>
    /// </summary>
    /// <事件类型> application.application.app_version.audit_v6 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 不支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/application-v6/application-app_version/events/audit">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取应用版本信息 (仅自建应用) </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// <ul>
    /// <li> 获取用户 user ID (仅自建应用) </li>
    /// </ul>
    /// </字段权限要求>
    public class AuditV6 : EventContext<AuditV6.EventData>
    {
        // EventData|operator_id:user_id|union_id:string||user_id:string||open_id:string||version_id:string||creator_id:user_id|union_id:string||user_id:string||open_id:string||app_id:string||operation:string||remark:string||audit_source:string|
        public class EventData
        {
            	
            /// <summary>
            /// 通过 / 拒绝应用审核的管理员 id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("operator_id")]
            public UserId OperatorId { get; init; }

            	
            /// <summary>
            /// 被审核的应用版本 id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("version_id")]
            public string VersionId { get; init; }

            	
            /// <summary>
            /// 应用创建者的 id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("creator_id")]
            public UserId CreatorId { get; init; }

            	
            /// <summary>
            /// 撤回应用的 id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("app_id")]
            public string AppId { get; init; }

            	
            /// <summary>
            /// 审核通过 / 拒绝
            /// 可选值有：
            /// audited：审核通过reject：审核拒绝
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("operation")]
            public string Operation { get; init; }

            	
            /// <summary>
            /// 审核信息，当审核拒绝时，管理员填写的拒绝理由
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("remark")]
            public string Remark { get; init; }

            	
            /// <summary>
            /// 应用审核的方式
            /// 可选值有：
            /// administrator：管理员审核auto：自动免审
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("audit_source")]
            public string AuditSource { get; init; }
        }

        // user_id|union_id:string||user_id:string||open_id:string|
        public class UserId
        {
            	
            /// <summary>
            /// 用户的 union id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// 用户的 user id
            /// 字段权限要求：
            /// 获取用户 user ID仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserIdValue { get; init; }

            	
            /// <summary>
            /// 用户的 open id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }
    }
}