// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Corehr.Department
{
    /// <summary>
    /// 【事件】删除部门<br/>
    /// 飞书人事中「部门被删除」时将触发此事件。<br/>
    /// </summary>
    /// <事件类型> corehr.department.deleted_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/department/events/deleted">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取核心人事信息 </li>
    /// <li> 获取部门信息 </li>
    /// <li> 读写部门信息 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class DeletedV1 : EventContext<DeletedV1.EventData>
    {
        // EventData|department_id:string|
        public class EventData
        {
            	
            /// <summary>
            /// 被删除部门的 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("department_id")]
            public string DepartmentId { get; init; }
        }
    }
}