// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Corehr.Department
{
    /// <summary>
    /// 【事件】更新部门<br/>
    /// 飞书人事中「部门信息被更新」时将触发此事件。注意：1. 触发时间为部门更新实际生效时间，如在 2022-01-01 更新部门，部门更新生效时间设置为 2022-05-01，事件将在 2022-05-01 进行推送。2. 只有在部门发生如下字段变更的时候，会触发「部门更新」事件：部门名称、code、部门描述、上级部门、部门子类型、部门负责人、是否保密、生效时间、失效时间、自定义字段（不包括其他部门角色）3. 删除部门不会触发「部门更新」事件<br/>
    /// </summary>
    /// <事件类型> corehr.department.updated_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/department/events/updated">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取核心人事信息 </li>
    /// <li> 获取部门信息 </li>
    /// <li> 读写部门信息 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class UpdatedV1 : EventContext<UpdatedV1.EventData>
    {
        // EventData|department_id:string||field_changes:string|
        public class EventData
        {
            	
            /// <summary>
            /// 被更新部门的 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("department_id")]
            public string DepartmentId { get; init; }

            	
            /// <summary>
            /// 发生变更的字段
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("field_changes")]
            public string[] FieldChanges { get; init; }
        }
    }
}