// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Corehr.Employment
{
    /// <summary>
    /// 员工完成转正<br/>
    /// 当员工转正完成时触发该事件<br/>
    /// </summary>
    /// <事件类型> corehr.employment.converted_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/employment/events/converted">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取核心人事信息 </li>
    /// <li> 获取雇佣信息 </li>
    /// <li> 读写雇佣信息 (仅自建应用) </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class ConvertedV1 : EventContext<ConvertedV1.EventData>
    {
        // EventData|employment_id:string|
        public class EventData
        {
            	
            /// <summary>
            /// 主对象ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("employment_id")]
            public string EmploymentId { get; init; }
        }
    }
}