// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace  FeishuNetSdk.FeishuEvent.V2.Application.Application
{
    /// <summary>
    /// 应用创建<br/>
    /// 当企业内有新的应用被创建时推送此事件<br/>
    /// </summary>
    /// <事件类型> application.application.created_v6 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 不支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/application-v6/application/events/created">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取应用信息 (仅自建应用) </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// <ul>
    /// <li> 获取用户 user ID (仅自建应用) </li>
    /// </ul>
    /// </字段权限要求>
    public class CreatedV6 : EventContext<CreatedV6.EventData>
    {
        // EventData|operator_id:user_id|union_id:string||user_id:string||open_id:string||app_id:string||name:string||description:string||avatar:string||app_scene_type:int||primary_language:string|
        public class EventData
        {
            	
            /// <summary>
            /// 用户 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("operator_id")]
            public UserId OperatorId { get; init; }

            	
            /// <summary>
            /// 应用 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("app_id")]
            public string AppId { get; init; }

            	
            /// <summary>
            /// 应用名称
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("name")]
            public string Name { get; init; }

            	
            /// <summary>
            /// 应用描述
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("description")]
            public string Description { get; init; }

            	
            /// <summary>
            /// 应用图标链接
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("avatar")]
            public string Avatar { get; init; }

            	
            /// <summary>
            /// 应用类型，0: 自建应用，1: 应用商店应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("app_scene_type")]
            public int AppSceneType { get; init; }

            	
            /// <summary>
            /// 应用主语言
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("primary_language")]
            public string PrimaryLanguage { get; init; }
        }

        // user_id|union_id:string||user_id:string||open_id:string|
        public class UserId
        {
            	
            /// <summary>
            /// 用户的 union id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// 用户的 user id
            /// 字段权限要求：
            /// 获取用户 user ID仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserIdValue { get; init; }

            	
            /// <summary>
            /// 用户的 open id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }
    }
}