// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Hire.ReferralAccount
{
    /// <summary>
    /// 账户余额变更<br/>
    /// 当内推账号余额发生变更时，触发该事件。<br/>
    /// </summary>
    /// <事件类型> hire.referral_account.assets_update_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/ukTMukTMukTM/uMzM1YjLzMTN24yMzUjN/hire-v1/referral_account/events/assets_update">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取内推账户信息 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class AssetsUpdateV1 : EventContext<AssetsUpdateV1.EventData>
    {
        // EventData|account_id:string||assets:assets|confirmed_bonus:bonus_amount|point_bonus:int||modify_time:string|
        public class EventData
        {
            	
            /// <summary>
            /// 账户ID， 同一用户在同一租户同一应用中账户唯一
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("account_id")]
            public string AccountId { get; init; }

            	
            /// <summary>
            /// 账户余额信息
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("assets")]
            public Assets Assets { get; init; }

            	
            /// <summary>
            /// 变更时间
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("modify_time")]
            public string ModifyTime { get; init; }
        }

        // assets|confirmed_bonus:bonus_amount|point_bonus:int|
        public class Assets
        {
            	
            /// <summary>
            /// 已确认的奖励
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("confirmed_bonus")]
            public BonusAmount ConfirmedBonus { get; init; }
        }

        // bonus_amount|point_bonus:int|
        public class BonusAmount
        {
            	
            /// <summary>
            /// 积分奖励
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("point_bonus")]
            public int PointBonus { get; init; }
        }
    }
}