// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Vc.Room
{
    /// <summary>
    /// 删除会议室<br/>
    /// 当删除会议室时，会触发该事件。<br/>
    /// </summary>
    /// <事件类型> vc.room.deleted_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/room/events/deleted">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 更新视频会议室信息 </li>
    /// <li> 获取视频会议室信息 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class DeletedV1 : EventContext<DeletedV1.EventData>
    {
        // EventData|room:room_event|room_id:string|
        public class EventData
        {
            	
            /// <summary>
            /// 会议室信息
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("room")]
            public RoomEvent Room { get; init; }
        }

        // room_event|room_id:string|
        public class RoomEvent
        {
            	
            /// <summary>
            /// 会议室ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("room_id")]
            public string RoomId { get; init; }
        }
    }
}