// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Vc.Room
{
    /// <summary>
    /// 更新会议室<br/>
    /// 当更新会议室时，会触发该事件。<br/>
    /// </summary>
    /// <事件类型> vc.room.updated_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/room/events/updated">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 更新视频会议室信息 </li>
    /// <li> 获取视频会议室信息 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class UpdatedV1 : EventContext<UpdatedV1.EventData>
    {
        // EventData|room:room_event|room_id:string||name:string||capacity:int||description:string||display_id:string||custom_room_id:string||room_level_id:string||path:string||room_status:room_status_event|status:boolean||schedule_status:boolean||disable_start_time:string||disable_end_time:string||disable_reason:string||contact_ids:user_id|union_id:string||user_id:string||open_id:string||disable_notice:boolean||resume_notice:boolean||device:device|name:string|
        public class EventData
        {
            	
            /// <summary>
            /// 会议室详情
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("room")]
            public RoomEvent Room { get; init; }
        }

        // room_event|room_id:string||name:string||capacity:int||description:string||display_id:string||custom_room_id:string||room_level_id:string||path:string||room_status:room_status_event|status:boolean||schedule_status:boolean||disable_start_time:string||disable_end_time:string||disable_reason:string||contact_ids:user_id|union_id:string||user_id:string||open_id:string||disable_notice:boolean||resume_notice:boolean||device:device|name:string|
        public class RoomEvent
        {
            	
            /// <summary>
            /// 会议室ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("room_id")]
            public string RoomId { get; init; }

            	
            /// <summary>
            /// 会议室名称
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("name")]
            public string Name { get; init; }

            	
            /// <summary>
            /// 会议室能容纳的人数
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("capacity")]
            public int Capacity { get; init; }

            	
            /// <summary>
            /// 会议室的相关描述
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("description")]
            public string Description { get; init; }

            	
            /// <summary>
            /// 会议室的展示ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("display_id")]
            public string DisplayId { get; init; }

            	
            /// <summary>
            /// 自定义的会议室ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("custom_room_id")]
            public string CustomRoomId { get; init; }

            	
            /// <summary>
            /// 层级ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("room_level_id")]
            public string RoomLevelId { get; init; }

            	
            /// <summary>
            /// 层级路径
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("path")]
            public string[] Path { get; init; }

            	
            /// <summary>
            /// 会议室状态
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("room_status")]
            public RoomStatusEvent RoomStatus { get; init; }

            	
            /// <summary>
            /// 设施信息列表
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("device")]
            public Device[] Device { get; init; }
        }

        // room_status_event|status:boolean||schedule_status:boolean||disable_start_time:string||disable_end_time:string||disable_reason:string||contact_ids:user_id|union_id:string||user_id:string||open_id:string||disable_notice:boolean||resume_notice:boolean|
        public class RoomStatusEvent
        {
            	
            /// <summary>
            /// 是否启用会议室
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("status")]
            public bool Status { get; init; }

            	
            /// <summary>
            /// 会议室未来状态为启用或禁用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("schedule_status")]
            public bool ScheduleStatus { get; init; }

            	
            /// <summary>
            /// 禁用开始时间（unix时间，单位sec）
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("disable_start_time")]
            public string DisableStartTime { get; init; }

            	
            /// <summary>
            /// 禁用结束时间（unix时间，单位sec，数值0表示永久禁用）
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("disable_end_time")]
            public string DisableEndTime { get; init; }

            	
            /// <summary>
            /// 禁用原因
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("disable_reason")]
            public string DisableReason { get; init; }

            	
            /// <summary>
            /// 联系人列表
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("contact_ids")]
            public UserId[] ContactIds { get; init; }

            	
            /// <summary>
            /// 是否在禁用时发送通知给预定了该会议室的员工
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("disable_notice")]
            public bool DisableNotice { get; init; }

            	
            /// <summary>
            /// 是否在恢复启用时发送通知给预定了该会议室的员工
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("resume_notice")]
            public bool ResumeNotice { get; init; }
        }

        // user_id|union_id:string||user_id:string||open_id:string|
        public class UserId
        {
            	
            /// <summary>
            /// 用户的 union id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// 用户的 user id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserIdValue { get; init; }

            	
            /// <summary>
            /// 用户的 open id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }

        // device|name:string|
        public class Device
        {
            	
            /// <summary>
            /// 设施名称
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("name")]
            public string Name { get; init; }
        }
    }
}