// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace  FeishuNetSdk.FeishuEvent.V2.Helpdesk.Notification
{
    /// <summary>
    /// 推送审核通知<br/>
    /// 推送审核状态通知事件。<br/>
    /// </summary>
    /// <事件类型> helpdesk.notification.approve_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 不支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/notification/events/approve">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取服务台资源详情 (仅自建应用) </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class ApproveV1 : EventContext<ApproveV1.EventData>
    {
        // EventData|notification_id:string||helpdesk_id:string||approve_status:string|
        public class EventData
        {
            	
            /// <summary>
            /// 推送任务唯一ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("notification_id")]
            public string NotificationId { get; init; }

            	
            /// <summary>
            /// 服务台唯一ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("helpdesk_id")]
            public string HelpdeskId { get; init; }

            	
            /// <summary>
            /// REJECTED(审核不通过)APPROVED(审核通过)CANCELED(取消审核)DELETED(删除审核)
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("approve_status")]
            public string ApproveStatus { get; init; }
        }
    }
}