// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Hire.EcoExam
{
    /// <summary>
    /// 创建笔试<br/>
    /// 用户在招聘系统安排笔试后，系统会推送事件给对应的开发者应用。开发者可根据事件获取候选人信息和试卷信息，并根据这些信息完成在三方服务商处的笔试订单创建。<br/>
    /// </summary>
    /// <事件类型> hire.eco_exam.created_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/ukTMukTMukTM/uMzM1YjLzMTN24yMzUjN/hire-v1/eco_exam/events/created">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 更新笔试信息 </li>
    /// <li> 获取笔试信息 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class CreatedV1 : EventContext<CreatedV1.EventData>
    {
        // EventData|exam_id:string||account_id:string||paper_id:string||candidate_info:eco_exam_create_event_candidate_info|name:string||mobile:eco_exam_create_event_mobile|code:string||number:string||email:string|
        public class EventData
        {
            	
            /// <summary>
            /// 笔试 ID，招聘系统内唯一
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("exam_id")]
            public string ExamId { get; init; }

            	
            /// <summary>
            /// 账号 ID，招聘系统内唯一
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("account_id")]
            public string AccountId { get; init; }

            	
            /// <summary>
            /// 试卷 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("paper_id")]
            public string PaperId { get; init; }

            	
            /// <summary>
            /// 候选人信息
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("candidate_info")]
            public EcoExamCreateEventCandidateInfo CandidateInfo { get; init; }
        }

        // eco_exam_create_event_candidate_info|name:string||mobile:eco_exam_create_event_mobile|code:string||number:string||email:string|
        public class EcoExamCreateEventCandidateInfo
        {
            	
            /// <summary>
            /// 候选人姓名
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("name")]
            public string Name { get; init; }

            	
            /// <summary>
            /// 候选人手机号
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("mobile")]
            public EcoExamCreateEventMobile Mobile { get; init; }

            	
            /// <summary>
            /// 候选人邮箱
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("email")]
            public string Email { get; init; }
        }

        // eco_exam_create_event_mobile|code:string||number:string|
        public class EcoExamCreateEventMobile
        {
            	
            /// <summary>
            /// 国家代码
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("code")]
            public string Code { get; init; }

            	
            /// <summary>
            /// 手机号码
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("number")]
            public string Number { get; init; }
        }
    }
}