// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Corehr.Process
{
    /// <summary>
    /// 流程实例信息变更<br/>
    /// 发起流程后会生成一个流程实例（process_id 是唯一标识）。流程中有审批人操作、流程数据更新、流程状态变化等都会触发事件，比如流程发起后，创建流程实例并生成节点每个人的待办任务，可能会触发多条事件。<br/>
    /// </summary>
    /// <事件类型> corehr.process.updated_v2 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/process/events/updated">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取流程数据 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class UpdatedV2 : EventContext<UpdatedV2.EventData>
    {
        // EventData|process_id:string||status:int||biz_type:string|
        public class EventData
        {
            	
            /// <summary>
            /// 流程实例ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("process_id")]
            public string ProcessId { get; init; }

            	
            /// <summary>
            /// 变更后状态：1 发起/进行中，9 完成，2拒绝，4 撤回，8 撤销
            /// 可选值有：
            /// 1：发起/进行中9：完成2：拒绝4：撤回8：撤销
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("status")]
            public int Status { get; init; }

            	
            /// <summary>
            /// 业务类型，详情请查看业务类型
            /// 数据校验规则：
            /// 长度范围：1 ～ 200 字符
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("biz_type")]
            public string BizType { get; init; }
        }
    }
}