// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Drive.File
{
    /// <summary>
    /// 多维表格字段变更<br/>
    /// 多维表格字段变更事件。被订阅的多维表格字段发生变更时，将会触发此事件。了解事件订阅的配置流程和使用场景，参考事件概述。<br/>
    /// </summary>
    /// <事件类型> drive.file.bitable_field_changed_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file/events/bitable_field_changed">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 查看、评论、编辑和管理多维表格 </li>
    /// <li> 查看、评论、编辑和管理云空间中所有文件 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// <ul>
    /// <li> 获取用户 user ID (仅自建应用) </li>
    /// </ul>
    /// </字段权限要求>
    public class BitableFieldChangedV1 : EventContext<BitableFieldChangedV1.EventData>
    {
        // EventData|file_type:string||file_token:string||table_id:string||operator_id:user_id|union_id:string||user_id:string||open_id:string||action_list:bitable.table.field_action|action:string||field_id:string||before_value:bitable.table.field_action.value|id:string||name:string||type:int||description:string||property:bitable.table.field_action.value.property|formatter:string||date_formatter:string||auto_fill:boolean||multiple:boolean||table_id:string||table_name:string||back_field_name:string||input_type:string||back_field_id:string||auto_serial:bitable.table.field_action.value.property.auto_serial|type:string||options:bitable.table.field_action.value.property.auto_serial.options|type:string||value:string||options:bitable.table.field_action.value.property.option|name:string||id:string||color:int||formula_expression:string||after_value:bitable.table.field_action.value|id:string||name:string||type:int||description:string||property:bitable.table.field_action.value.property|formatter:string||date_formatter:string||auto_fill:boolean||multiple:boolean||table_id:string||table_name:string||back_field_name:string||input_type:string||back_field_id:string||auto_serial:bitable.table.field_action.value.property.auto_serial|type:string||options:bitable.table.field_action.value.property.auto_serial.options|type:string||value:string||options:bitable.table.field_action.value.property.option|name:string||id:string||color:int||formula_expression:string||revision:int||subscriber_id_list:user_id|union_id:string||user_id:string||open_id:string||update_time:int|
        public class EventData
        {
            	
            /// <summary>
            /// 文档类型
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("file_type")]
            public string FileType { get; init; }

            	
            /// <summary>
            /// 文档token
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("file_token")]
            public string FileToken { get; init; }

            	
            /// <summary>
            /// 多维表格数据表ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("table_id")]
            public string TableId { get; init; }

            	
            /// <summary>
            /// 用户 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("operator_id")]
            public UserId OperatorId { get; init; }

            	
            /// <summary>
            /// 字段变更操作列表
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("action_list")]
            public BitableTableFieldAction[] ActionList { get; init; }

            	
            /// <summary>
            /// 多维表格数据表的版本号
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("revision")]
            public int Revision { get; init; }

            	
            /// <summary>
            /// 订阅用户id列表
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("subscriber_id_list")]
            public UserId[] SubscriberIdList { get; init; }

            	
            /// <summary>
            /// 字段变更时间
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("update_time")]
            public int UpdateTime { get; init; }
        }

        // user_id|union_id:string||user_id:string||open_id:string|
        public class UserId
        {
            	
            /// <summary>
            /// 用户的 union id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// 用户的 user id
            /// 字段权限要求：
            /// 获取用户 user ID仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserIdValue { get; init; }

            	
            /// <summary>
            /// 用户的 open id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }

        // bitable.table.field_action|action:string||field_id:string||before_value:bitable.table.field_action.value|id:string||name:string||type:int||description:string||property:bitable.table.field_action.value.property|formatter:string||date_formatter:string||auto_fill:boolean||multiple:boolean||table_id:string||table_name:string||back_field_name:string||input_type:string||back_field_id:string||auto_serial:bitable.table.field_action.value.property.auto_serial|type:string||options:bitable.table.field_action.value.property.auto_serial.options|type:string||value:string||options:bitable.table.field_action.value.property.option|name:string||id:string||color:int||formula_expression:string||after_value:bitable.table.field_action.value|id:string||name:string||type:int||description:string||property:bitable.table.field_action.value.property|formatter:string||date_formatter:string||auto_fill:boolean||multiple:boolean||table_id:string||table_name:string||back_field_name:string||input_type:string||back_field_id:string||auto_serial:bitable.table.field_action.value.property.auto_serial|type:string||options:bitable.table.field_action.value.property.auto_serial.options|type:string||value:string||options:bitable.table.field_action.value.property.option|name:string||id:string||color:int||formula_expression:string|
        public class BitableTableFieldAction
        {
            	
            /// <summary>
            /// 操作类型，action目前有三种，field_added表示有新增字段操作，field_edited表示有更新字段操作，field_delete表示有删除字段操作
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("action")]
            public string Action { get; init; }

            	
            /// <summary>
            /// 字段 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("field_id")]
            public string FieldId { get; init; }

            	
            /// <summary>
            /// 操作前的字段值
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("before_value")]
            public BitableTableFieldActionValue BeforeValue { get; init; }

            	
            /// <summary>
            /// 操作后的字段值
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("after_value")]
            public BitableTableFieldActionValue AfterValue { get; init; }
        }

        // bitable.table.field_action.value|id:string||name:string||type:int||description:string||property:bitable.table.field_action.value.property|formatter:string||date_formatter:string||auto_fill:boolean||multiple:boolean||table_id:string||table_name:string||back_field_name:string||input_type:string||back_field_id:string||auto_serial:bitable.table.field_action.value.property.auto_serial|type:string||options:bitable.table.field_action.value.property.auto_serial.options|type:string||value:string||options:bitable.table.field_action.value.property.option|name:string||id:string||color:int||formula_expression:string|
        public class BitableTableFieldActionValue
        {
            	
            /// <summary>
            /// 字段 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("id")]
            public string Id { get; init; }

            	
            /// <summary>
            /// 字段名字
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("name")]
            public string Name { get; init; }

            	
            /// <summary>
            /// 字段类型
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("type")]
            public int Type { get; init; }

            	
            /// <summary>
            /// 字段描述
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("description")]
            public string Description { get; init; }

            	
            /// <summary>
            /// 字段属性
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("property")]
            public BitableTableFieldActionValueProperty Property { get; init; }
        }

        // bitable.table.field_action.value.property|formatter:string||date_formatter:string||auto_fill:boolean||multiple:boolean||table_id:string||table_name:string||back_field_name:string||input_type:string||back_field_id:string||auto_serial:bitable.table.field_action.value.property.auto_serial|type:string||options:bitable.table.field_action.value.property.auto_serial.options|type:string||value:string||options:bitable.table.field_action.value.property.option|name:string||id:string||color:int||formula_expression:string|
        public class BitableTableFieldActionValueProperty
        {
            	
            /// <summary>
            /// 数字、公式字段的显示格式
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("formatter")]
            public string Formatter { get; init; }

            	
            /// <summary>
            /// 日期、创建时间、最后更新时间字段的显示格式
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("date_formatter")]
            public string DateFormatter { get; init; }

            	
            /// <summary>
            /// 日期字段中新纪录自动填写创建时间
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("auto_fill")]
            public bool AutoFill { get; init; }

            	
            /// <summary>
            /// 人员字段中允许添加多个成员，单向关联、双向关联中允许添加多个记录
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("multiple")]
            public bool Multiple { get; init; }

            	
            /// <summary>
            /// 单向关联、双向关联字段中关联的数据表的ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("table_id")]
            public string TableId { get; init; }

            	
            /// <summary>
            /// 单向关联、双向关联字段中关联的数据表的名字
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("table_name")]
            public string TableName { get; init; }

            	
            /// <summary>
            /// 双向关联字段中关联的数据表中对应的双向关联字段的名字
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("back_field_name")]
            public string BackFieldName { get; init; }

            	
            /// <summary>
            /// 地理位置输入限制
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("input_type")]
            public string InputType { get; init; }

            	
            /// <summary>
            /// 双向关联字段中关联的数据表中对应的双向关联字段的id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("back_field_id")]
            public string BackFieldId { get; init; }

            	
            /// <summary>
            /// 自动编号类型
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("auto_serial")]
            public BitableTableFieldActionValuePropertyAutoSerial AutoSerial { get; init; }

            	
            /// <summary>
            /// 单选、多选字段的选项信息
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("options")]
            public BitableTableFieldActionValuePropertyOption[] Options { get; init; }

            	
            /// <summary>
            /// 公式字段的公式表达式
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("formula_expression")]
            public string FormulaExpression { get; init; }
        }

        // bitable.table.field_action.value.property.auto_serial|type:string||options:bitable.table.field_action.value.property.auto_serial.options|type:string||value:string|
        public class BitableTableFieldActionValuePropertyAutoSerial
        {
            	
            /// <summary>
            /// 自动编号类型
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("type")]
            public string Type { get; init; }

            	
            /// <summary>
            /// 自动编号规则列表
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("options")]
            public BitableTableFieldActionValuePropertyAutoSerialOptions[] Options { get; init; }
        }

        // bitable.table.field_action.value.property.auto_serial.options|type:string||value:string|
        public class BitableTableFieldActionValuePropertyAutoSerialOptions
        {
            	
            /// <summary>
            /// 自动编号的可选规则项类型
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("type")]
            public string Type { get; init; }

            	
            /// <summary>
            /// 与类型相对应的取值
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("value")]
            public string Value { get; init; }
        }

        // bitable.table.field_action.value.property.option|name:string||id:string||color:int|
        public class BitableTableFieldActionValuePropertyOption
        {
            	
            /// <summary>
            /// 选项名
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("name")]
            public string Name { get; init; }

            	
            /// <summary>
            /// 选项ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("id")]
            public string Id { get; init; }

            	
            /// <summary>
            /// 选项颜色
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("color")]
            public int Color { get; init; }
        }
    }
}