// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Im.Message
{
    /// <summary>
    /// 撤回消息<br/>
    /// 消息被撤回后触发此事件。<br/>
    /// </summary>
    /// <事件类型> im.message.recalled_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/events/recalled">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取与发送单聊、群组消息 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class RecalledV1 : EventContext<RecalledV1.EventData>
    {
        // EventData|message_id:string||chat_id:string||recall_time:string||recall_type:string|
        public class EventData
        {
            	
            /// <summary>
            /// 消息ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("message_id")]
            public string MessageId { get; init; }

            	
            /// <summary>
            /// 群ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("chat_id")]
            public string ChatId { get; init; }

            	
            /// <summary>
            /// 撤回时间
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("recall_time")]
            public string RecallTime { get; init; }

            	
            /// <summary>
            /// 撤回类型
            /// 可选值有：
            /// message_owner：消息发送者撤回group_owner：群主撤回group_manager：群管理员撤回enterprise_manager：企业管理员撤回
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("recall_type")]
            public string RecallType { get; init; }
        }
    }
}