// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace  FeishuNetSdk.FeishuEvent.V2.Calendar.Calendar.Acl
{
    /// <summary>
    /// 删除 ACL<br/>
    /// 当订阅的日历上有访问控制被删除时，将会触发此事件。<br/>
    /// </summary>
    /// <事件类型> calendar.calendar.acl.deleted_v4 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar-acl/events/deleted">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 更新日历及日程信息 </li>
    /// <li> 获取日历、日程及忙闲信息 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// <ul>
    /// <li> 获取用户 user ID (仅自建应用) </li>
    /// </ul>
    /// </字段权限要求>
    public class DeletedV4 : EventContext<DeletedV4.CalendarAclEvent>
    {
        // calendar.acl_event|acl_id:string||role:string||scope:acl_scope_event|type:string||user_id:user_id|union_id:string||user_id:string||open_id:string||user_id_list:user_id|union_id:string||user_id:string||open_id:string|
        public class CalendarAclEvent
        {
            	
            /// <summary>
            /// 访问控制 ID。该 ID 在单个日历实体内唯一，不同日历实体可能存在重复的访问控制 ID。
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("acl_id")]
            public string AclId { get; init; }

            	
            /// <summary>
            /// 对日历的访问权限。
            /// 可选值有：
            /// unknown：未知权限。free_busy_reader：游客，只能看到忙碌、空闲信息。reader：订阅者，可查看所有日程详情。writer：编辑者，可创建及修改日程。owner：管理员，可管理日历及共享设置。
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("role")]
            public string Role { get; init; }

            	
            /// <summary>
            /// 权限生效范围。
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("scope")]
            public AclScopeEvent Scope { get; init; }

            	
            /// <summary>
            /// 需要推送事件的用户列表。
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id_list")]
            public UserId[] UserIdList { get; init; }
        }

        // acl_scope_event|type:string||user_id:user_id|union_id:string||user_id:string||open_id:string|
        public class AclScopeEvent
        {
            	
            /// <summary>
            /// 权限生效范围的类型。
            /// 可选值有：
            /// user：用户
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("type")]
            public string Type { get; init; }

            	
            /// <summary>
            /// 用户 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public UserId UserId { get; init; }
        }

        // user_id|union_id:string||user_id:string||open_id:string|
        public class UserId
        {
            	
            /// <summary>
            /// 用户的 union id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// 用户的 user id
            /// 字段权限要求：
            /// 获取用户 user ID仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserIdValue { get; init; }

            	
            /// <summary>
            /// 用户的 open id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }
    }
}