// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Hire.Offer
{
    /// <summary>
    /// Offer 状态变更<br/>
    /// 当 Offer 状态发生变更时将触发该事件。<br/>
    /// </summary>
    /// <事件类型> hire.offer.status_changed_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/ukTMukTMukTM/uMzM1YjLzMTN24yMzUjN/hire-v1/offer/events/status_changed">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 查看 offer 的基础信息 </li>
    /// <li> 获取 offer 信息 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class StatusChangedV1 : EventContext<StatusChangedV1.EventData>
    {
        // EventData|offer_id:string|
        public class EventData
        {
            	
            /// <summary>
            /// 发生状态变更的 OfferID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("offer_id")]
            public string OfferId { get; init; }
        }
    }
}