// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace  FeishuNetSdk.FeishuEvent.V2.Im.Message.Reaction
{
    /// <summary>
    /// 新增消息表情回复<br/>
    /// 消息被添加某一个表情回复后触发此事件。<br/>
    /// </summary>
    /// <事件类型> im.message.reaction.created_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message-reaction/events/created">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取单聊、群组消息 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// <ul>
    /// <li> 获取用户 user ID (仅自建应用) </li>
    /// </ul>
    /// </字段权限要求>
    public class CreatedV1 : EventContext<CreatedV1.EventData>
    {
        // EventData|message_id:string||reaction_type:emoji|emoji_type:string||operator_type:string||user_id:user_id|union_id:string||user_id:string||open_id:string||app_id:string||action_time:string|
        public class EventData
        {
            	
            /// <summary>
            /// 消息的 open_message_id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("message_id")]
            public string MessageId { get; init; }

            	
            /// <summary>
            /// 表情回复的资源类型
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("reaction_type")]
            public Emoji ReactionType { get; init; }

            	
            /// <summary>
            /// 操作人类型
            /// 注意事项：
            /// 如果操作人类型是"user"，则会返回 user_id如果操作人类型是"app"，则会返回 app_id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("operator_type")]
            public string OperatorType { get; init; }

            	
            /// <summary>
            /// 用户 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public UserId UserId { get; init; }

            	
            /// <summary>
            /// 应用 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("app_id")]
            public string AppId { get; init; }

            	
            /// <summary>
            /// 添加表情回复时间戳（单位：ms）
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("action_time")]
            public string ActionTime { get; init; }
        }

        // emoji|emoji_type:string|
        public class Emoji
        {
            	
            /// <summary>
            /// emoji类型 emoji类型列举
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("emoji_type")]
            public string EmojiType { get; init; }
        }

        // user_id|union_id:string||user_id:string||open_id:string|
        public class UserId
        {
            	
            /// <summary>
            /// 用户的 union id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// 用户的 user id
            /// 字段权限要求：
            /// 获取用户 user ID仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserIdValue { get; init; }

            	
            /// <summary>
            /// 用户的 open id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }
    }
}