// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Acs.AccessRecord
{
    /// <summary>
    /// 新增门禁访问记录<br/>
    /// 门禁设备识别用户成功后发送该事件给订阅应用。<br/>
    /// </summary>
    /// <事件类型> acs.access_record.created_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/acs-v1/access_record/events/created">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 查看智能门禁记录 (仅自建应用) </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// <ul>
    /// <li> 获取用户 user ID (仅自建应用) </li>
    /// </ul>
    /// </字段权限要求>
    public class CreatedV1 : EventContext<CreatedV1.EventData>
    {
        // EventData|access_record_id:string||user_id:user_id|union_id:string||user_id:string||open_id:string||device_id:string||is_clock_in:boolean||is_door_open:boolean||access_time:string|
        public class EventData
        {
            	
            /// <summary>
            /// 门禁记录 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("access_record_id")]
            public string AccessRecordId { get; init; }

            	
            /// <summary>
            /// 用户 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public UserId UserId { get; init; }

            	
            /// <summary>
            /// 设备 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("device_id")]
            public string DeviceId { get; init; }

            	
            /// <summary>
            /// 是否打卡
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("is_clock_in")]
            public bool IsClockIn { get; init; }

            	
            /// <summary>
            /// 是否开门
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("is_door_open")]
            public bool IsDoorOpen { get; init; }

            	
            /// <summary>
            /// 识别时间 （单位：秒）
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("access_time")]
            public string AccessTime { get; init; }
        }

        // user_id|union_id:string||user_id:string||open_id:string|
        public class UserId
        {
            	
            /// <summary>
            /// 用户的 union id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// 用户的 user id
            /// 字段权限要求：
            /// 获取用户 user ID仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserIdValue { get; init; }

            	
            /// <summary>
            /// 用户的 open id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }
    }
}