// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Corehr.PreHire
{
    /// <summary>
    /// 待入职人员信息变更<br/>
    /// 待入职人员信息更新后，触发此事件。<br/>
    /// </summary>
    /// <事件类型> corehr.pre_hire.updated_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/pre_hire/events/updated">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取待入职人员信息 </li>
    /// <li> 读写待入职人员信息 (仅自建应用) </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class UpdatedV1 : EventContext<UpdatedV1.EventData>
    {
        // EventData|pre_hire_id:string||field_changes:string|
        public class EventData
        {
            	
            /// <summary>
            /// 待入职 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("pre_hire_id")]
            public string PreHireId { get; init; }

            	
            /// <summary>
            /// 变更的字段
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("field_changes")]
            public string[] FieldChanges { get; init; }
        }
    }
}