// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Hire.EhrImportTaskForInternshipOffer
{
    /// <summary>
    /// 导入 e-HR（实习 Offer）<br/>
    /// 飞书招聘系统内用户选择实习 Offer 导入 e-HR 系统之后，将推送候选人信息至订阅系统中。可以使用实习 Offer id更新实习 Offer 入/离职状态搭配使用：更新 e-HR 导入任务结果更新本次导入事件的结果<br/>
    /// </summary>
    /// <事件类型> hire.ehr_import_task_for_internship_offer.imported_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 不支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/ukTMukTMukTM/uMzM1YjLzMTN24yMzUjN/hire-v1/ehr_import_task_for_internship_offer/events/imported">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 更新导入 e-HR 任务 (仅自建应用) </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// <ul>
    /// <li> 获取用户 user ID (仅自建应用) </li>
    /// </ul>
    /// </字段权限要求>
    public class ImportedV1 : EventContext<ImportedV1.EventData>
    {
        // EventData|task_id:string||application_id:string||offer_id:string||pre_onboard_id:string||ehr_department_id:string||operator_id:string||operator_user_id:user_id|union_id:string||user_id:string||open_id:string||ehr_department:department_id|department_id:string||open_department_id:string|
        public class EventData
        {
            	
            /// <summary>
            /// 导入任务 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("task_id")]
            public string TaskId { get; init; }

            	
            /// <summary>
            /// 投递 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("application_id")]
            public string ApplicationId { get; init; }

            	
            /// <summary>
            /// Offer ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("offer_id")]
            public string OfferId { get; init; }

            	
            /// <summary>
            /// 实习 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("pre_onboard_id")]
            public string PreOnboardId { get; init; }

            	
            /// <summary>
            /// 导入部门 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("ehr_department_id")]
            public string EhrDepartmentId { get; init; }

            	
            /// <summary>
            /// 操作人的飞书招聘 user_id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("operator_id")]
            public string OperatorId { get; init; }

            	
            /// <summary>
            /// 用户 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("operator_user_id")]
            public UserId OperatorUserId { get; init; }

            	
            /// <summary>
            /// saas 部门ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("ehr_department")]
            public DepartmentId EhrDepartment { get; init; }
        }

        // user_id|union_id:string||user_id:string||open_id:string|
        public class UserId
        {
            	
            /// <summary>
            /// 用户的 union id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// 用户的 user id
            /// 字段权限要求：
            /// 获取用户 user ID仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserIdValue { get; init; }

            	
            /// <summary>
            /// 用户的 open id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }

        // department_id|department_id:string||open_department_id:string|
        public class DepartmentId
        {
            	
            /// <summary>
            /// 部门ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("department_id")]
            public string DepartmentIdValue { get; init; }

            	
            /// <summary>
            /// 部门 Open ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_department_id")]
            public string OpenDepartmentId { get; init; }
        }
    }
}