// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace  FeishuNetSdk.FeishuEvent.V2.Helpdesk.TicketMessage
{
    /// <summary>
    /// 工单消息事件<br/>
    /// 该消息事件属于工单消息事件。需使用订阅接口订阅：事件订阅。<br/>
    /// </summary>
    /// <事件类型> helpdesk.ticket_message.created_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 不支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/ticket_message/events/created">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取服务台资源详情 (仅自建应用) </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// <ul>
    /// <li> 获取用户 user ID (仅自建应用) </li>
    /// </ul>
    /// </字段权限要求>
    public class CreatedV1 : EventContext<CreatedV1.TicketMessageEvent>
    {
        // ticket_message_event|ticket_message_id:string||message_id:string||msg_type:string||position:string||sender_id:user_id|union_id:string||user_id:string||open_id:string||sender_type:int||text:string||ticket:ticket|ticket_id:string||comments:comments|content:string||created_at:int||id:int||user_avatar_url:string||user_name:string||user_id:int||ticket_type:int||status:int||dissatisfaction_reason:i18n|zh_cn:string||en_us:string||ja_jp:string||customized_fields:customized_field_display_item|id:string||value:string||key_name:string||display_name:string||position:int||required:boolean||editable:boolean||agent_service_duration:float||agent_first_response_duration:int||bot_service_duration:int||agent_resolution_time:int||actual_processing_time:int||agent_entry_time:int||agent_first_response_time:int||agent_last_response_time:int||agent_owner:ticket_user|id:string||avatar_url:string||name:string||email:string||department:string||city:string||country:string||event_id:string||chat_id:string||content:ticket_message_content|content:string||msg_type:string||image_keys:string||image_key:string|
        public class TicketMessageEvent
        {
            	
            /// <summary>
            /// ticket message id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("ticket_message_id")]
            public string TicketMessageId { get; init; }

            	
            /// <summary>
            /// open message id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("message_id")]
            public string MessageId { get; init; }

            	
            /// <summary>
            /// message type, text is the only supported type
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("msg_type")]
            public string MsgType { get; init; }

            	
            /// <summary>
            /// position of the message
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("position")]
            public string Position { get; init; }

            	
            /// <summary>
            /// 用户 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("sender_id")]
            public UserId SenderId { get; init; }

            	
            /// <summary>
            /// sender type, 1 for bot, 2 for guest, 3 for agent
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("sender_type")]
            public int SenderType { get; init; }

            	
            /// <summary>
            /// message content
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("text")]
            public string Text { get; init; }

            	
            /// <summary>
            /// ticket related information
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("ticket")]
            public Ticket Ticket { get; init; }

            	
            /// <summary>
            /// event id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("event_id")]
            public string EventId { get; init; }

            	
            /// <summary>
            /// chat id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("chat_id")]
            public string ChatId { get; init; }

            	
            /// <summary>
            /// message content
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("content")]
            public TicketMessageContent Content { get; init; }
        }

        // user_id|union_id:string||user_id:string||open_id:string|
        public class UserId
        {
            	
            /// <summary>
            /// 用户的 union id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// 用户的 user id
            /// 字段权限要求：
            /// 获取用户 user ID仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserIdValue { get; init; }

            	
            /// <summary>
            /// 用户的 open id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }

        // ticket|ticket_id:string||comments:comments|content:string||created_at:int||id:int||user_avatar_url:string||user_name:string||user_id:int||ticket_type:int||status:int||dissatisfaction_reason:i18n|zh_cn:string||en_us:string||ja_jp:string||customized_fields:customized_field_display_item|id:string||value:string||key_name:string||display_name:string||position:int||required:boolean||editable:boolean||agent_service_duration:float||agent_first_response_duration:int||bot_service_duration:int||agent_resolution_time:int||actual_processing_time:int||agent_entry_time:int||agent_first_response_time:int||agent_last_response_time:int||agent_owner:ticket_user|id:string||avatar_url:string||name:string||email:string||department:string||city:string||country:string|
        public class Ticket
        {
            	
            /// <summary>
            /// 工单ID
            /// 可以从工单列表里面取
            /// 也可以订阅工单创建事件获取
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("ticket_id")]
            public string TicketId { get; init; }

            	
            /// <summary>
            /// 备注
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("comments")]
            public Comments Comments { get; init; }

            	
            /// <summary>
            /// 工单阶段：1. 机器人 2. 人工
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("ticket_type")]
            public int TicketType { get; init; }

            	
            /// <summary>
            /// 工单状态，1：已创建 2: 处理中 3: 排队中 4：待定 5：待用户响应 50: 被机器人关闭 51: 被客服关闭 52: 用户自己关闭
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("status")]
            public int Status { get; init; }

            	
            /// <summary>
            /// 不满意原因
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("dissatisfaction_reason")]
            public I18n DissatisfactionReason { get; init; }

            	
            /// <summary>
            /// 自定义字段列表，没有值时不设置下拉菜单的value对应工单字段里面的children.display_name获取全部工单自定义字段
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("customized_fields")]
            public CustomizedFieldDisplayItem[] CustomizedFields { get; init; }

            	
            /// <summary>
            /// 客服服务时长，客服最后一次回复时间距离客服进入时间间隔，单位分钟
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("agent_service_duration")]
            public float AgentServiceDuration { get; init; }

            	
            /// <summary>
            /// 客服首次回复时间距离客服进入时间的间隔(秒)
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("agent_first_response_duration")]
            public int AgentFirstResponseDuration { get; init; }

            	
            /// <summary>
            /// 机器人服务时间：客服进入时间距离工单创建时间的间隔，单位秒
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("bot_service_duration")]
            public int BotServiceDuration { get; init; }

            	
            /// <summary>
            /// 客服解决时长，关单时间距离客服进入时间的间隔，单位秒
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("agent_resolution_time")]
            public int AgentResolutionTime { get; init; }

            	
            /// <summary>
            /// 工单实际处理时间：从客服进入到关单，单位秒
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("actual_processing_time")]
            public int ActualProcessingTime { get; init; }

            	
            /// <summary>
            /// 客服进入时间，单位毫秒
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("agent_entry_time")]
            public int AgentEntryTime { get; init; }

            	
            /// <summary>
            /// 客服首次回复时间，单位毫秒
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("agent_first_response_time")]
            public int AgentFirstResponseTime { get; init; }

            	
            /// <summary>
            /// 客服最后回复时间，单位毫秒
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("agent_last_response_time")]
            public int AgentLastResponseTime { get; init; }

            	
            /// <summary>
            /// 主责客服
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("agent_owner")]
            public TicketUser AgentOwner { get; init; }
        }

        // comments|content:string||created_at:int||id:int||user_avatar_url:string||user_name:string||user_id:int|
        public class Comments
        {
            	
            /// <summary>
            /// 备注
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("content")]
            public string Content { get; init; }

            	
            /// <summary>
            /// 备注时间，单位毫秒
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("created_at")]
            public int CreatedAt { get; init; }

            	
            /// <summary>
            /// 备注ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("id")]
            public int Id { get; init; }

            	
            /// <summary>
            /// 备注人头像
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_avatar_url")]
            public string UserAvatarUrl { get; init; }

            	
            /// <summary>
            /// 备注人姓名
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_name")]
            public string UserName { get; init; }

            	
            /// <summary>
            /// 备注人ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public int UserId { get; init; }
        }

        // i18n|zh_cn:string||en_us:string||ja_jp:string|
        public class I18n
        {
            	
            /// <summary>
            /// 中文描述
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("zh_cn")]
            public string ZhCn { get; init; }

            	
            /// <summary>
            /// 英文描述
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("en_us")]
            public string EnUs { get; init; }

            	
            /// <summary>
            /// 日文描述
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("ja_jp")]
            public string JaJp { get; init; }
        }

        // customized_field_display_item|id:string||value:string||key_name:string||display_name:string||position:int||required:boolean||editable:boolean|
        public class CustomizedFieldDisplayItem
        {
            	
            /// <summary>
            /// 自定义字段ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("id")]
            public string Id { get; init; }

            	
            /// <summary>
            /// 自定义字段值
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("value")]
            public string Value { get; init; }

            	
            /// <summary>
            /// 键名
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("key_name")]
            public string KeyName { get; init; }

            	
            /// <summary>
            /// 展示名称
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("display_name")]
            public string DisplayName { get; init; }

            	
            /// <summary>
            /// 展示位置
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("position")]
            public int Position { get; init; }

            	
            /// <summary>
            /// 是否必填
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("required")]
            public bool Required { get; init; }

            	
            /// <summary>
            /// 是否可修改
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("editable")]
            public bool Editable { get; init; }
        }

        // ticket_user|id:string||avatar_url:string||name:string||email:string||department:string||city:string||country:string|
        public class TicketUser
        {
            	
            /// <summary>
            /// 用户ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("id")]
            public string Id { get; init; }

            	
            /// <summary>
            /// 用户头像url
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("avatar_url")]
            public string AvatarUrl { get; init; }

            	
            /// <summary>
            /// 用户名
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("name")]
            public string Name { get; init; }

            	
            /// <summary>
            /// 用户邮箱
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("email")]
            public string Email { get; init; }

            	
            /// <summary>
            /// 所在部门名称
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("department")]
            public string Department { get; init; }

            	
            /// <summary>
            /// 城市
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("city")]
            public string City { get; init; }

            	
            /// <summary>
            /// 国家代号(CountryCode)，参考：http://www.mamicode.com/info-detail-2186501.html
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("country")]
            public string Country { get; init; }
        }

        // ticket_message_content|content:string||msg_type:string||image_keys:string||image_key:string|
        public class TicketMessageContent
        {
            	
            /// <summary>
            /// 内容
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("content")]
            public string Content { get; init; }

            	
            /// <summary>
            /// 消息类型；text：纯文本；post：富文本；image：图片
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("msg_type")]
            public string MsgType { get; init; }

            	
            /// <summary>
            /// 图片ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("image_keys")]
            public string[] ImageKeys { get; init; }

            	
            /// <summary>
            /// 图片ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("image_key")]
            public string ImageKey { get; init; }
        }
    }
}