// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Contact.User
{
    /// <summary>
    /// 员工离职<br/>
    /// 通过该事件订阅员工离职。应用身份访问通讯录的权限为历史版本，不推荐申请。<br/>
    /// </summary>
    /// <事件类型> contact.user.deleted_v3 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/contact-v3/user/events/deleted">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取通讯录基本信息 </li>
    /// <li> 以应用身份读取通讯录 </li>
    /// <li> 以应用身份访问通讯录 (历史版本) </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// <ul>
    /// <li> 以应用身份读取通讯录 </li>
    /// <li> 获取用户基本信息 </li>
    /// <li> 获取用户组织架构信息 </li>
    /// <li> 查看成员的虚线上级 ID </li>
    /// <li> 获取用户受雇信息 </li>
    /// <li> 查看成员工号 </li>
    /// <li> 获取用户性别 </li>
    /// <li> 查询用户职级 (仅自建应用) </li>
    /// <li> 获取用户 user ID (仅自建应用) </li>
    /// <li> 获取用户手机号 (仅自建应用) </li>
    /// <li> 获取用户邮箱信息 (仅自建应用) </li>
    /// <li> 查询用户所属的工作序列 (仅自建应用) </li>
    /// <li> 以应用身份访问通讯录 (历史版本) </li>
    /// <li> 读取通讯录 (历史版本) </li>
    /// </ul>
    /// </字段权限要求>
    public class DeletedV3 : EventContext<DeletedV3.EventData>
    {
        // EventData|object:user_event|open_id:string||union_id:string||user_id:string||name:string||en_name:string||nickname:string||email:string||enterprise_email:string||job_title:string||mobile:string||gender:int||avatar:avatar_info|avatar_72:string||avatar_240:string||avatar_640:string||avatar_origin:string||status:user_status|is_frozen:boolean||is_resigned:boolean||is_activated:boolean||is_exited:boolean||is_unjoin:boolean||department_ids:string||leader_user_id:string||city:string||country:string||work_station:string||join_time:int||employee_no:string||employee_type:int||orders:user_order|department_id:string||user_order:int||department_order:int||is_primary_dept:boolean||custom_attrs:user_custom_attr|type:string||id:string||value:user_custom_attr_value|text:string||url:string||pc_url:string||option_id:string||option_value:string||name:string||picture_url:string||generic_user:custom_attr_generic_user|id:string||type:int||job_level_id:string||job_family_id:string||dotted_line_leader_user_ids:string||old_object:old_user_object|department_ids:string||open_id:string|
        public class EventData
        {
            	
            /// <summary>
            /// 员工信息
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("object")]
            public UserEvent Object { get; init; }

            	
            /// <summary>
            /// 删除前信息
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("old_object")]
            public OldUserObject OldObject { get; init; }
        }

        // user_event|open_id:string||union_id:string||user_id:string||name:string||en_name:string||nickname:string||email:string||enterprise_email:string||job_title:string||mobile:string||gender:int||avatar:avatar_info|avatar_72:string||avatar_240:string||avatar_640:string||avatar_origin:string||status:user_status|is_frozen:boolean||is_resigned:boolean||is_activated:boolean||is_exited:boolean||is_unjoin:boolean||department_ids:string||leader_user_id:string||city:string||country:string||work_station:string||join_time:int||employee_no:string||employee_type:int||orders:user_order|department_id:string||user_order:int||department_order:int||is_primary_dept:boolean||custom_attrs:user_custom_attr|type:string||id:string||value:user_custom_attr_value|text:string||url:string||pc_url:string||option_id:string||option_value:string||name:string||picture_url:string||generic_user:custom_attr_generic_user|id:string||type:int||job_level_id:string||job_family_id:string||dotted_line_leader_user_ids:string|
        public class UserEvent
        {
            	
            /// <summary>
            /// 用户的open_id 用户相关的 ID 概念
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }

            	
            /// <summary>
            /// 用户的union_id 用户相关的 ID 概念
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// 租户内用户的唯一标识 用户相关的 ID 概念
            /// 字段权限要求：
            /// 获取用户 user ID仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserId { get; init; }

            	
            /// <summary>
            /// 用户名
            /// 数据校验规则：
            /// 最小长度：1 字符
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取用户基本信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("name")]
            public string Name { get; init; }

            	
            /// <summary>
            /// 英文名
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取用户基本信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("en_name")]
            public string EnName { get; init; }

            	
            /// <summary>
            /// 别名
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取用户基本信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("nickname")]
            public string Nickname { get; init; }

            	
            /// <summary>
            /// 邮箱
            /// 字段权限要求：
            /// 获取用户邮箱信息仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("email")]
            public string Email { get; init; }

            	
            /// <summary>
            /// 企业邮箱
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取用户基本信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("enterprise_email")]
            public string EnterpriseEmail { get; init; }

            	
            /// <summary>
            /// 职务
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("job_title")]
            public string JobTitle { get; init; }

            	
            /// <summary>
            /// 手机号
            /// 字段权限要求：
            /// 获取用户手机号仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("mobile")]
            public string Mobile { get; init; }

            	
            /// <summary>
            /// 性别
            /// 可选值有：
            /// 0：未知1：男2：女3：其他
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取用户性别
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("gender")]
            public int Gender { get; init; }

            	
            /// <summary>
            /// 用户头像信息
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取用户基本信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("avatar")]
            public AvatarInfo Avatar { get; init; }

            	
            /// <summary>
            /// 用户状态
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取用户受雇信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("status")]
            public UserStatus Status { get; init; }

            	
            /// <summary>
            /// 用户所属部门的ID列表
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取用户组织架构信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("department_ids")]
            public string[] DepartmentIds { get; init; }

            	
            /// <summary>
            /// 用户的直接主管的用户open_id 用户相关的 ID 概念
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取用户受雇信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("leader_user_id")]
            public string LeaderUserId { get; init; }

            	
            /// <summary>
            /// 城市
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取用户受雇信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("city")]
            public string City { get; init; }

            	
            /// <summary>
            /// 国家
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取用户受雇信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("country")]
            public string Country { get; init; }

            	
            /// <summary>
            /// 工位
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取用户受雇信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("work_station")]
            public string WorkStation { get; init; }

            	
            /// <summary>
            /// 入职时间
            /// 数据校验规则：
            /// 取值范围：1 ～ 2147483647
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取用户受雇信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("join_time")]
            public int JoinTime { get; init; }

            	
            /// <summary>
            /// 工号
            /// 字段权限要求（满足任一）：
            /// 获取用户受雇信息
            /// 查看成员工号
            /// 以应用身份读取通讯录
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("employee_no")]
            public string EmployeeNo { get; init; }

            	
            /// <summary>
            /// 员工类型
            /// 可选值有：
            /// 1：正式员工2：实习生3：外包4：劳务5：顾问
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取用户受雇信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("employee_type")]
            public int EmployeeType { get; init; }

            	
            /// <summary>
            /// 用户排序信息
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取用户组织架构信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("orders")]
            public UserOrder[] Orders { get; init; }

            	
            /// <summary>
            /// 自定义属性
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取用户受雇信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("custom_attrs")]
            public UserCustomAttr[] CustomAttrs { get; init; }

            	
            /// <summary>
            /// 职级ID
            /// 字段权限要求：
            /// 查询用户职级仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("job_level_id")]
            public string JobLevelId { get; init; }

            	
            /// <summary>
            /// 序列ID
            /// 字段权限要求：
            /// 查询用户所属的工作序列仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("job_family_id")]
            public string JobFamilyId { get; init; }

            	
            /// <summary>
            /// 虚线上级ID
            /// 字段权限要求：
            /// 查看成员的虚线上级 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("dotted_line_leader_user_ids")]
            public string[] DottedLineLeaderUserIds { get; init; }
        }

        // avatar_info|avatar_72:string||avatar_240:string||avatar_640:string||avatar_origin:string|
        public class AvatarInfo
        {
            	
            /// <summary>
            /// 72*72像素头像链接
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("avatar_72")]
            public string Avatar72 { get; init; }

            	
            /// <summary>
            /// 240*240像素头像链接
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("avatar_240")]
            public string Avatar240 { get; init; }

            	
            /// <summary>
            /// 640*640像素头像链接
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("avatar_640")]
            public string Avatar640 { get; init; }

            	
            /// <summary>
            /// 原始头像链接
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("avatar_origin")]
            public string AvatarOrigin { get; init; }
        }

        // user_status|is_frozen:boolean||is_resigned:boolean||is_activated:boolean||is_exited:boolean||is_unjoin:boolean|
        public class UserStatus
        {
            	
            /// <summary>
            /// 是否暂停
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("is_frozen")]
            public bool IsFrozen { get; init; }

            	
            /// <summary>
            /// 是否离职
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("is_resigned")]
            public bool IsResigned { get; init; }

            	
            /// <summary>
            /// 是否激活
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("is_activated")]
            public bool IsActivated { get; init; }

            	
            /// <summary>
            /// 是否主动退出，主动退出一段时间后用户会自动转为已离职
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("is_exited")]
            public bool IsExited { get; init; }

            	
            /// <summary>
            /// 是否未加入，需要用户自主确认才能加入团队
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("is_unjoin")]
            public bool IsUnjoin { get; init; }
        }

        // user_order|department_id:string||user_order:int||department_order:int||is_primary_dept:boolean|
        public class UserOrder
        {
            	
            /// <summary>
            /// 排序信息对应的部门ID， ID值与查询参数中的department_id_type 对应。
            /// 表示用户所在的、且需要排序的部门。
            /// 不同 ID 的说明参见及获取方式参见 部门ID说明
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("department_id")]
            public string DepartmentId { get; init; }

            	
            /// <summary>
            /// 用户在其直属部门内的排序，数值越大，排序越靠前
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_order")]
            public int UserOrderValue { get; init; }

            	
            /// <summary>
            /// 用户所属的多个部门间的排序，数值越大，排序越靠前
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("department_order")]
            public int DepartmentOrder { get; init; }

            	
            /// <summary>
            /// 标识用户的唯一主部门，主部门为用户所属部门中排序第一的部门(department_order最大)
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("is_primary_dept")]
            public bool IsPrimaryDept { get; init; }
        }

        // user_custom_attr|type:string||id:string||value:user_custom_attr_value|text:string||url:string||pc_url:string||option_id:string||option_value:string||name:string||picture_url:string||generic_user:custom_attr_generic_user|id:string||type:int|
        public class UserCustomAttr
        {
            	
            /// <summary>
            /// 自定义字段类型
            /// TEXT：文本HREF：网页ENUMERATION：枚举PICTURE_ENUM：图片GENERIC_USER：用户
            /// 具体说明参见常见问题的用户接口相关问题
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("type")]
            public string Type { get; init; }

            	
            /// <summary>
            /// 自定义字段ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("id")]
            public string Id { get; init; }

            	
            /// <summary>
            /// 自定义字段取值
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("value")]
            public UserCustomAttrValue Value { get; init; }
        }

        // user_custom_attr_value|text:string||url:string||pc_url:string||option_id:string||option_value:string||name:string||picture_url:string||generic_user:custom_attr_generic_user|id:string||type:int|
        public class UserCustomAttrValue
        {
            	
            /// <summary>
            /// 字段类型为TEXT时该参数定义字段值，必填；字段类型为HREF时该参数定义网页标题，必填
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("text")]
            public string Text { get; init; }

            	
            /// <summary>
            /// 字段类型为 HREF 时，该参数定义默认 URL，例如手机端跳转小程序，PC端跳转网页
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("url")]
            public string Url { get; init; }

            	
            /// <summary>
            /// 字段类型为 HREF 时，该参数定义PC端 URL
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("pc_url")]
            public string PcUrl { get; init; }

            	
            /// <summary>
            /// 字段类型为 ENUMERATION 或 PICTURE_ENUM 时，该参数定义选项值
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("option_id")]
            public string OptionId { get; init; }

            	
            /// <summary>
            /// 选项类型的值。
            /// 表示 成员详情/自定义字段 中选项选中的值
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("option_value")]
            public string OptionValue { get; init; }

            	
            /// <summary>
            /// 选项类型为图片时，表示图片的名称
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("name")]
            public string Name { get; init; }

            	
            /// <summary>
            /// 图片链接
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("picture_url")]
            public string PictureUrl { get; init; }

            	
            /// <summary>
            /// 字段类型为 GENERIC_USER 时，该参数定义引用人员
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("generic_user")]
            public CustomAttrGenericUser GenericUser { get; init; }
        }

        // custom_attr_generic_user|id:string||type:int|
        public class CustomAttrGenericUser
        {
            	
            /// <summary>
            /// 用户的user_id ，具体参见用户相关的 ID 概念
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("id")]
            public string Id { get; init; }

            	
            /// <summary>
            /// 用户类型:1：用户
            /// 目前固定为1，表示用户类型
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("type")]
            public int Type { get; init; }
        }

        // old_user_object|department_ids:string||open_id:string|
        public class OldUserObject
        {
            	
            /// <summary>
            /// 用户所属部门的ID列表
            /// 字段权限要求（满足任一）：
            /// 以应用身份读取通讯录
            /// 获取用户组织架构信息
            /// 以应用身份访问通讯录历史版本
            /// 读取通讯录历史版本
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("department_ids")]
            public string[] DepartmentIds { get; init; }

            	
            /// <summary>
            /// 用户open_id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }
    }
}