// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace  FeishuNetSdk.FeishuEvent.V2.Corehr.Process.Node
{
    /// <summary>
    /// 流程节点状态变更<br/>
    /// 配置的节点为节点定义（node_definition_id 是唯一标识）。在流程实例中，每个流程实例生成的节点实例会不同。<br/>
    /// </summary>
    /// <事件类型> corehr.process.node.updated_v2 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/process-node/events/updated">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取流程数据 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class UpdatedV2 : EventContext<UpdatedV2.EventData>
    {
        // EventData|flow_definition_id:string||node_definition_id:string||process_id:string||process_node_id:string||node_type:int||node_status:int||biz_type:string|
        public class EventData
        {
            	
            /// <summary>
            /// 流程定义 id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("flow_definition_id")]
            public string FlowDefinitionId { get; init; }

            	
            /// <summary>
            /// 节点定义 id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("node_definition_id")]
            public string NodeDefinitionId { get; init; }

            	
            /// <summary>
            /// 流程运行实例 id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("process_id")]
            public string ProcessId { get; init; }

            	
            /// <summary>
            /// 节点运行实例 id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("process_node_id")]
            public string ProcessNodeId { get; init; }

            	
            /// <summary>
            /// 节点类型
            /// 可选值有：
            /// 1：审批节点2：抄送节点5：表单节点6：电子签
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("node_type")]
            public int NodeType { get; init; }

            	
            /// <summary>
            /// 节点状态
            /// 可选值有：
            /// 1：进行中2：已拒绝3：已通过4：已撤回5：已回退
            /// 展开
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("node_status")]
            public int NodeStatus { get; init; }

            	
            /// <summary>
            /// 业务类型，详情请查看业务类型
            /// 数据校验规则：
            /// 长度范围：1 ～ 200 字符
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("biz_type")]
            public string BizType { get; init; }
        }
    }
}