// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace  FeishuNetSdk.FeishuEvent.V2.MeetingRoom.MeetingRoom
{
    /// <summary>
    /// 会议室创建<br/>
    /// 会议室被创建将触发此事件。<br/>
    /// </summary>
    /// <事件类型> meeting_room.meeting_room.created_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/meeting_room-v1/meeting_room/events/created">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取会议室信息 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class CreatedV1 : EventContext<CreatedV1.EventData>
    {
        // EventData|room_name:string||room_id:string|
        public class EventData
        {
            	
            /// <summary>
            /// 会议室名称
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("room_name")]
            public string RoomName { get; init; }

            	
            /// <summary>
            /// 会议室 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("room_id")]
            public string RoomId { get; init; }
        }
    }
}