// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Hire.EcoBackgroundCheck
{
    /// <summary>
    /// 终止背调<br/>
    /// 用户在招聘系统终止背调后，系统会推送事件给对应的应用开发者。开发者可根据事件获取背调 ID，完成在三方服务商处的订单取消等后续操作。<br/>
    /// </summary>
    /// <事件类型> hire.eco_background_check.canceled_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/ukTMukTMukTM/uMzM1YjLzMTN24yMzUjN/hire-v1/eco_background_check/events/canceled">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取招聘背调信息 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class CanceledV1 : EventContext<CanceledV1.EventData>
    {
        // EventData|background_check_id:string||termination_reason:string|
        public class EventData
        {
            	
            /// <summary>
            /// 背调 ID，招聘系统内唯一
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("background_check_id")]
            public string BackgroundCheckId { get; init; }

            	
            /// <summary>
            /// 终止原因
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("termination_reason")]
            public string TerminationReason { get; init; }
        }
    }
}