// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Hire.EcoBackgroundCheck
{
    /// <summary>
    /// 创建背调<br/>
    /// 用户在招聘系统安排背调后，系统会推送事件给对应的应用开发者。开发者可根据事件获取候选人信息、委托人信息和自定义字段信息，并根据这些信息完成在三方服务商处的背调订单创建。<br/>
    /// </summary>
    /// <事件类型> hire.eco_background_check.created_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/ukTMukTMukTM/uMzM1YjLzMTN24yMzUjN/hire-v1/eco_background_check/events/created">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取招聘背调信息 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class CreatedV1 : EventContext<CreatedV1.EventData>
    {
        // EventData|background_check_id:string||account_id:string||package_id:string||additional_item_id_list:string||comment:string||candidate_info:eco_background_check_create_event_candidate_info|name:string||mobile:eco_background_check_create_event_mobile|code:string||number:string||email:string||first_name:string||last_name:string||client_contact_info:eco_background_check_create_event_contact_info|name:string||mobile:eco_background_check_create_event_mobile|code:string||number:string||email:string||custom_field_list:eco_background_check_create_event_custom_kv|key:string||value:string|
        public class EventData
        {
            	
            /// <summary>
            /// 背调 ID，招聘系统内唯一
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("background_check_id")]
            public string BackgroundCheckId { get; init; }

            	
            /// <summary>
            /// 账号 ID，招聘系统内唯一
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("account_id")]
            public string AccountId { get; init; }

            	
            /// <summary>
            /// 套餐 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("package_id")]
            public string PackageId { get; init; }

            	
            /// <summary>
            /// 附件调查项 ID 列表
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("additional_item_id_list")]
            public string[] AdditionalItemIdList { get; init; }

            	
            /// <summary>
            /// 备注
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("comment")]
            public string Comment { get; init; }

            	
            /// <summary>
            /// 候选人信息
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("candidate_info")]
            public EcoBackgroundCheckCreateEventCandidateInfo CandidateInfo { get; init; }

            	
            /// <summary>
            /// 联系人（委托人）信息
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("client_contact_info")]
            public EcoBackgroundCheckCreateEventContactInfo ClientContactInfo { get; init; }

            	
            /// <summary>
            /// 自定义字段键值对
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("custom_field_list")]
            public EcoBackgroundCheckCreateEventCustomKv[] CustomFieldList { get; init; }
        }

        // eco_background_check_create_event_candidate_info|name:string||mobile:eco_background_check_create_event_mobile|code:string||number:string||email:string||first_name:string||last_name:string|
        public class EcoBackgroundCheckCreateEventCandidateInfo
        {
            	
            /// <summary>
            /// 候选人姓名
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("name")]
            public string Name { get; init; }

            	
            /// <summary>
            /// 候选人手机号
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("mobile")]
            public EcoBackgroundCheckCreateEventMobile Mobile { get; init; }

            	
            /// <summary>
            /// 候选人邮箱
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("email")]
            public string Email { get; init; }

            	
            /// <summary>
            /// 名字
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("first_name")]
            public string FirstName { get; init; }

            	
            /// <summary>
            /// 姓氏
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("last_name")]
            public string LastName { get; init; }
        }

        // eco_background_check_create_event_mobile|code:string||number:string|
        public class EcoBackgroundCheckCreateEventMobile
        {
            	
            /// <summary>
            /// 国家代码
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("code")]
            public string Code { get; init; }

            	
            /// <summary>
            /// 手机号码
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("number")]
            public string Number { get; init; }
        }

        // eco_background_check_create_event_contact_info|name:string||mobile:eco_background_check_create_event_mobile|code:string||number:string||email:string|
        public class EcoBackgroundCheckCreateEventContactInfo
        {
            	
            /// <summary>
            /// 联系人姓名
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("name")]
            public string Name { get; init; }

            	
            /// <summary>
            /// 联系人手机号
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("mobile")]
            public EcoBackgroundCheckCreateEventMobile Mobile { get; init; }

            	
            /// <summary>
            /// 联系人邮箱
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("email")]
            public string Email { get; init; }
        }

        // eco_background_check_create_event_custom_kv|key:string||value:string|
        public class EcoBackgroundCheckCreateEventCustomKv
        {
            	
            /// <summary>
            /// 自定义字段标识
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("key")]
            public string Key { get; init; }

            	
            /// <summary>
            /// 自定义字段值
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("value")]
            public string Value { get; init; }
        }
    }
}