// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Im.Chat
{
    /// <summary>
    /// 群配置修改<br/>
    /// 群组配置被修改后触发此事件，包含：群主转移群基本信息修改(群头像/群名称/群描述/群国际化名称)群权限修改(加人入群权限/群编辑权限/at所有人权限/群分享权限等)<br/>
    /// </summary>
    /// <事件类型> im.chat.updated_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat/events/updated">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取与更新群组信息 </li>
    /// <li> 获取群组信息 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// <ul>
    /// <li> 获取用户 user ID (仅自建应用) </li>
    /// </ul>
    /// </字段权限要求>
    public class UpdatedV1 : EventContext<UpdatedV1.EventData>
    {
        // EventData|chat_id:string||operator_id:user_id|union_id:string||user_id:string||open_id:string||external:boolean||operator_tenant_key:string||after_change:chat_change|avatar:string||name:string||description:string||i18n_names:i18n_names|zh_cn:string||en_us:string||ja_jp:string||add_member_permission:string||share_card_permission:string||at_all_permission:string||edit_permission:string||membership_approval:string||join_message_visibility:string||leave_message_visibility:string||moderation_permission:string||owner_id:user_id|union_id:string||user_id:string||open_id:string||restricted_mode_setting:restricted_mode_setting|status:boolean||screenshot_has_permission_setting:string||download_has_permission_setting:string||message_has_permission_setting:string||group_message_type:string||before_change:chat_change|avatar:string||name:string||description:string||i18n_names:i18n_names|zh_cn:string||en_us:string||ja_jp:string||add_member_permission:string||share_card_permission:string||at_all_permission:string||edit_permission:string||membership_approval:string||join_message_visibility:string||leave_message_visibility:string||moderation_permission:string||owner_id:user_id|union_id:string||user_id:string||open_id:string||restricted_mode_setting:restricted_mode_setting|status:boolean||screenshot_has_permission_setting:string||download_has_permission_setting:string||message_has_permission_setting:string||group_message_type:string||moderator_list:moderator_list|added_member_list:list_event_moderator|tenant_key:string||user_id:user_id|union_id:string||user_id:string||open_id:string||removed_member_list:list_event_moderator|tenant_key:string||user_id:user_id|union_id:string||user_id:string||open_id:string|
        public class EventData
        {
            	
            /// <summary>
            /// 群组 ID，详情参见群ID 说明
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("chat_id")]
            public string ChatId { get; init; }

            	
            /// <summary>
            /// 用户 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("operator_id")]
            public UserId OperatorId { get; init; }

            	
            /// <summary>
            /// 是否是外部群
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("external")]
            public bool External { get; init; }

            	
            /// <summary>
            /// 操作者租户 Key
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("operator_tenant_key")]
            public string OperatorTenantKey { get; init; }

            	
            /// <summary>
            /// 更新后的群信息
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("after_change")]
            public ChatChange AfterChange { get; init; }

            	
            /// <summary>
            /// 更新前的群信息
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("before_change")]
            public ChatChange BeforeChange { get; init; }

            	
            /// <summary>
            /// 群可发言成员名单的变更信息
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("moderator_list")]
            public ModeratorList ModeratorList { get; init; }
        }

        // user_id|union_id:string||user_id:string||open_id:string|
        public class UserId
        {
            	
            /// <summary>
            /// 用户的 union id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// 用户的 user id
            /// 字段权限要求：
            /// 获取用户 user ID仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserIdValue { get; init; }

            	
            /// <summary>
            /// 用户的 open id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }

        // chat_change|avatar:string||name:string||description:string||i18n_names:i18n_names|zh_cn:string||en_us:string||ja_jp:string||add_member_permission:string||share_card_permission:string||at_all_permission:string||edit_permission:string||membership_approval:string||join_message_visibility:string||leave_message_visibility:string||moderation_permission:string||owner_id:user_id|union_id:string||user_id:string||open_id:string||restricted_mode_setting:restricted_mode_setting|status:boolean||screenshot_has_permission_setting:string||download_has_permission_setting:string||message_has_permission_setting:string||group_message_type:string|
        public class ChatChange
        {
            	
            /// <summary>
            /// 群头像
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("avatar")]
            public string Avatar { get; init; }

            	
            /// <summary>
            /// 群名称
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("name")]
            public string Name { get; init; }

            	
            /// <summary>
            /// 群描述
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("description")]
            public string Description { get; init; }

            	
            /// <summary>
            /// 群国际化名称
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("i18n_names")]
            public I18nNames I18nNames { get; init; }

            	
            /// <summary>
            /// 加人入群权限(all_members/only_owner/unknown)
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("add_member_permission")]
            public string AddMemberPermission { get; init; }

            	
            /// <summary>
            /// 群分享权限(allowed/not_allowed/unknown)
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("share_card_permission")]
            public string ShareCardPermission { get; init; }

            	
            /// <summary>
            /// at 所有人权限(all_members/only_owner/unknown)
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("at_all_permission")]
            public string AtAllPermission { get; init; }

            	
            /// <summary>
            /// 群编辑权限(all_members/only_owner/unknown)
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("edit_permission")]
            public string EditPermission { get; init; }

            	
            /// <summary>
            /// 加群审批(no_approval_required/approval_required)
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("membership_approval")]
            public string MembershipApproval { get; init; }

            	
            /// <summary>
            /// 入群消息可见性(only_owner/all_members/not_anyone)
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("join_message_visibility")]
            public string JoinMessageVisibility { get; init; }

            	
            /// <summary>
            /// 出群消息可见性(only_owner/all_members/not_anyone)
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("leave_message_visibility")]
            public string LeaveMessageVisibility { get; init; }

            	
            /// <summary>
            /// 发言权限(all_members/only_owner)
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("moderation_permission")]
            public string ModerationPermission { get; init; }

            	
            /// <summary>
            /// 用户 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("owner_id")]
            public UserId OwnerId { get; init; }

            	
            /// <summary>
            /// 防泄密模式设置
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("restricted_mode_setting")]
            public RestrictedModeSetting RestrictedModeSetting { get; init; }

            	
            /// <summary>
            /// 群消息形式（chat/thread）
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("group_message_type")]
            public string GroupMessageType { get; init; }
        }

        // i18n_names|zh_cn:string||en_us:string||ja_jp:string|
        public class I18nNames
        {
            	
            /// <summary>
            /// 中文名
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("zh_cn")]
            public string ZhCn { get; init; }

            	
            /// <summary>
            /// 英文名
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("en_us")]
            public string EnUs { get; init; }

            	
            /// <summary>
            /// 日文名
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("ja_jp")]
            public string JaJp { get; init; }
        }

        // restricted_mode_setting|status:boolean||screenshot_has_permission_setting:string||download_has_permission_setting:string||message_has_permission_setting:string|
        public class RestrictedModeSetting
        {
            	
            /// <summary>
            /// 防泄密模式是否开启
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("status")]
            public bool Status { get; init; }

            	
            /// <summary>
            /// 允许截屏录屏
            /// 可选值有：
            /// all_members：所有成员允许截屏录屏not_anyone：所有成员禁止截屏录屏
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("screenshot_has_permission_setting")]
            public string ScreenshotHasPermissionSetting { get; init; }

            	
            /// <summary>
            /// 允许下载消息中图片、视频和文件
            /// 可选值有：
            /// all_members：所有成员允许下载资源not_anyone：所有成员禁止下载资源
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("download_has_permission_setting")]
            public string DownloadHasPermissionSetting { get; init; }

            	
            /// <summary>
            /// 允许复制和转发消息
            /// 可选值有：
            /// all_members：所有成员允许复制和转发消息not_anyone：所有成员禁止复制和转发消息
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("message_has_permission_setting")]
            public string MessageHasPermissionSetting { get; init; }
        }

        // moderator_list|added_member_list:list_event_moderator|tenant_key:string||user_id:user_id|union_id:string||user_id:string||open_id:string||removed_member_list:list_event_moderator|tenant_key:string||user_id:user_id|union_id:string||user_id:string||open_id:string|
        public class ModeratorList
        {
            	
            /// <summary>
            /// 被添加进可发言名单的用户列表（列表中一定会有owner）
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("added_member_list")]
            public ListEventModerator[] AddedMemberList { get; init; }

            	
            /// <summary>
            /// 被移除出可发言名单的用户列表
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("removed_member_list")]
            public ListEventModerator[] RemovedMemberList { get; init; }
        }

        // list_event_moderator|tenant_key:string||user_id:user_id|union_id:string||user_id:string||open_id:string|
        public class ListEventModerator
        {
            	
            /// <summary>
            /// 租户 Key
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("tenant_key")]
            public string TenantKey { get; init; }

            	
            /// <summary>
            /// 用户 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public UserId UserId { get; init; }
        }
    }
}