// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace  FeishuNetSdk.FeishuEvent.V2.Helpdesk.Ticket
{
    /// <summary>
    /// 创建工单<br/>
    /// 可监听服务台的工单创建事件。需使用订阅接口订阅：事件订阅<br/>
    /// </summary>
    /// <事件类型> helpdesk.ticket.created_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 不支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/ticket/events/created">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取服务台资源详情 (仅自建应用) </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// <ul>
    /// <li> 获取用户 user ID (仅自建应用) </li>
    /// </ul>
    /// </字段权限要求>
    public class CreatedV1 : EventContext<CreatedV1.TicketEvent>
    {
        // ticket_event|ticket_id:string||helpdesk_id:string||guest:ticket_user_event|id:user_id|union_id:string||user_id:string||open_id:string||name:string||stage:int||status:int||score:int||created_at:int||updated_at:int||closed_at:int||channel:int||solve:int||customized_fields:customized_field_display_item|id:string||value:string||key_name:string||display_name:string||position:int||required:boolean||editable:boolean||chat_id:string|
        public class TicketEvent
        {
            	
            /// <summary>
            /// 工单ID
            /// 可以从工单列表里面取
            /// 也可以订阅工单创建事件获取
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("ticket_id")]
            public string TicketId { get; init; }

            	
            /// <summary>
            /// 服务台id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("helpdesk_id")]
            public string HelpdeskId { get; init; }

            	
            /// <summary>
            /// 用户id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("guest")]
            public TicketUserEvent Guest { get; init; }

            	
            /// <summary>
            /// 工单阶段：1. 机器人 2. 人工
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("stage")]
            public int Stage { get; init; }

            	
            /// <summary>
            /// 工单状态，1：已创建 2: 处理中 3: 排队中 4：待定 5：待用户响应 50: 被机器人关闭 51: 被客服关闭 52: 用户自己关闭
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("status")]
            public int Status { get; init; }

            	
            /// <summary>
            /// 工单评分，1：不满意，2:一般，3:满意
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("score")]
            public int Score { get; init; }

            	
            /// <summary>
            /// 创建时间
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("created_at")]
            public int CreatedAt { get; init; }

            	
            /// <summary>
            /// 工单更新时间，没有值时为-1
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("updated_at")]
            public int UpdatedAt { get; init; }

            	
            /// <summary>
            /// 关单时间
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("closed_at")]
            public int ClosedAt { get; init; }

            	
            /// <summary>
            /// 工单渠道，描述：9：Open API 2：二维码 14：分享 13：搜索 其他数字：其他渠道
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("channel")]
            public int Channel { get; init; }

            	
            /// <summary>
            /// 工单是否解决 1:没解决 2:已解决
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("solve")]
            public int Solve { get; init; }

            	
            /// <summary>
            /// 自定义字段
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("customized_fields")]
            public CustomizedFieldDisplayItem[] CustomizedFields { get; init; }

            	
            /// <summary>
            /// oc_xxxxxxx
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("chat_id")]
            public string ChatId { get; init; }
        }

        // ticket_user_event|id:user_id|union_id:string||user_id:string||open_id:string||name:string|
        public class TicketUserEvent
        {
            	
            /// <summary>
            /// id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("id")]
            public UserId Id { get; init; }

            	
            /// <summary>
            /// 名称
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("name")]
            public string Name { get; init; }
        }

        // user_id|union_id:string||user_id:string||open_id:string|
        public class UserId
        {
            	
            /// <summary>
            /// 用户的 union id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// 用户的 user id
            /// 字段权限要求：
            /// 获取用户 user ID仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserIdValue { get; init; }

            	
            /// <summary>
            /// 用户的 open id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }

        // customized_field_display_item|id:string||value:string||key_name:string||display_name:string||position:int||required:boolean||editable:boolean|
        public class CustomizedFieldDisplayItem
        {
            	
            /// <summary>
            /// 自定义字段ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("id")]
            public string Id { get; init; }

            	
            /// <summary>
            /// 自定义字段值
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("value")]
            public string Value { get; init; }

            	
            /// <summary>
            /// 键名
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("key_name")]
            public string KeyName { get; init; }

            	
            /// <summary>
            /// 展示名称
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("display_name")]
            public string DisplayName { get; init; }

            	
            /// <summary>
            /// 展示位置
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("position")]
            public int Position { get; init; }

            	
            /// <summary>
            /// 是否必填
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("required")]
            public bool Required { get; init; }

            	
            /// <summary>
            /// 是否可修改
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("editable")]
            public bool Editable { get; init; }
        }
    }
}