// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Contact.CustomAttrEvent
{
    /// <summary>
    /// 成员字段变更<br/>
    /// 通过该事件订阅成员字段变更。old_object 展示更新字段的原始值。<br/>
    /// </summary>
    /// <事件类型> contact.custom_attr_event.updated_v3 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/contact-v3/custom_attr_event/events/updated">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取通讯录基本信息 </li>
    /// <li> 以应用身份读取通讯录 </li>
    /// <li> 以应用身份访问通讯录 (历史版本) </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class UpdatedV3 : EventContext<UpdatedV3.EventData>
    {
        // EventData|object:custom_attr_event|contact_field_key:string||allow_open_query:boolean||old_object:custom_attr_event|contact_field_key:string||allow_open_query:boolean|
        public class EventData
        {
            	
            /// <summary>
            /// 变更后信息
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("object")]
            public CustomAttrEvent Object { get; init; }

            	
            /// <summary>
            /// 变更前信息
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("old_object")]
            public CustomAttrEvent OldObject { get; init; }
        }

        // custom_attr_event|contact_field_key:string||allow_open_query:boolean|
        public class CustomAttrEvent
        {
            	
            /// <summary>
            /// 通讯录字段键值
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("contact_field_key")]
            public string[] ContactFieldKey { get; init; }

            	
            /// <summary>
            /// 开关是否打开
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("allow_open_query")]
            public bool AllowOpenQuery { get; init; }
        }
    }
}