// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace  FeishuNetSdk.FeishuEvent.V2.Corehr.Process.Cc
{
    /// <summary>
    /// 抄送单据状态变更<br/>
    /// 抄送节点会生成抄送单据任务。如果一个节点有多个人抄送人，则会生成多个抄送单据。<br/>
    /// </summary>
    /// <事件类型> corehr.process.cc.updated_v2 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/process-cc/events/updated">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取流程数据 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class UpdatedV2 : EventContext<UpdatedV2.EventData>
    {
        // EventData|process_id:string||approver_id:string||status:int||biz_type:string|
        public class EventData
        {
            	
            /// <summary>
            /// 流程实例ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("process_id")]
            public string ProcessId { get; init; }

            	
            /// <summary>
            /// 抄送单据ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("approver_id")]
            public string ApproverId { get; init; }

            	
            /// <summary>
            /// 单据状态
            /// 可选值有：
            /// 5：抄送到达
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("status")]
            public int Status { get; init; }

            	
            /// <summary>
            /// 业务类型，详情请查看业务类型
            /// 数据校验规则：
            /// 长度范围：1 ～ 200 字符
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("biz_type")]
            public string BizType { get; init; }
        }
    }
}