// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Vc.RoomLevel
{
    /// <summary>
    /// 更新会议室层级<br/>
    /// 当更新会议室层级时，会触发该事件。<br/>
    /// </summary>
    /// <事件类型> vc.room_level.updated_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/room_level/events/updated">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 更新视频会议室信息 </li>
    /// <li> 获取视频会议室信息 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class UpdatedV1 : EventContext<UpdatedV1.EventData>
    {
        // EventData|room_level:room_level|room_level_id:string||name:string||parent_id:string||path:string||has_child:boolean||custom_group_id:string|
        public class EventData
        {
            	
            /// <summary>
            /// 层级信息
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("room_level")]
            public RoomLevel RoomLevel { get; init; }
        }

        // room_level|room_level_id:string||name:string||parent_id:string||path:string||has_child:boolean||custom_group_id:string|
        public class RoomLevel
        {
            	
            /// <summary>
            /// 层级ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("room_level_id")]
            public string RoomLevelId { get; init; }

            	
            /// <summary>
            /// 层级名称
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("name")]
            public string Name { get; init; }

            	
            /// <summary>
            /// 父层级ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("parent_id")]
            public string ParentId { get; init; }

            	
            /// <summary>
            /// 层级路径
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("path")]
            public string[] Path { get; init; }

            	
            /// <summary>
            /// 是否有子层级
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("has_child")]
            public bool HasChild { get; init; }

            	
            /// <summary>
            /// 自定义层级ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("custom_group_id")]
            public string CustomGroupId { get; init; }
        }
    }
}