// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Corehr.Job
{
    /// <summary>
    /// 创建职务<br/>
    /// 飞书人事中「职务被创建」时将触发此事件。<br/>
    /// </summary>
    /// <事件类型> corehr.job.created_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/job/events/created">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取核心人事信息 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class CreatedV1 : EventContext<CreatedV1.EventData>
    {
        // EventData|job_id:string|
        public class EventData
        {
            	
            /// <summary>
            /// Job ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("job_id")]
            public string JobId { get; init; }
        }
    }
}