// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace  FeishuNetSdk.FeishuEvent.V2.Application.Application.Feedback
{
    /// <summary>
    /// 新增应用反馈<br/>
    /// 当应用收到新反馈时，触发该事件<br/>
    /// </summary>
    /// <事件类型> application.application.feedback.created_v6 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/application-v6/application-feedback/events/created">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 管理应用反馈数据 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// <ul>
    /// <li> 获取用户邮箱信息 (仅自建应用) </li>
    /// <li> 获取用户 user ID (仅自建应用) </li>
    /// <li> 获取用户手机号 (仅自建应用) </li>
    /// </ul>
    /// </字段权限要求>
    public class CreatedV6 : EventContext<CreatedV6.EventData>
    {
        // EventData|user_id:user_id|union_id:string||user_id:string||open_id:string||app_id:string||feedback_time:string||tenant_name:string||feedback_type:int||fault_type:int||fault_time:string||source:int||contact:string||description:string||images:string||feedback_id:string||feedback_path:string|
        public class EventData
        {
            	
            /// <summary>
            /// 用户 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public UserId UserId { get; init; }

            	
            /// <summary>
            /// 被反馈应用 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("app_id")]
            public string AppId { get; init; }

            	
            /// <summary>
            /// 反馈提交时间，格式为yyyy-mm-dd hh:mm:ss
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("feedback_time")]
            public string FeedbackTime { get; init; }

            	
            /// <summary>
            /// 反馈用户的租户名
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("tenant_name")]
            public string TenantName { get; init; }

            	
            /// <summary>
            /// 反馈类型（枚举值，1：故障反馈，2：产品建议）
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("feedback_type")]
            public int FeedbackType { get; init; }

            	
            /// <summary>
            /// 故障类型列表：1: 黑屏 2: 白屏 3: 无法打开小程序  4: 卡顿 5: 小程序闪退 6: 页面加载慢 7: 死机 8: 其他异常
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("fault_type")]
            public int[] FaultType { get; init; }

            	
            /// <summary>
            /// 故障时间，格式为yyyy-mm-dd hh:mm:ss
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("fault_time")]
            public string FaultTime { get; init; }

            	
            /// <summary>
            /// 反馈来源：1： 小程序 2：网页应用 3：机器人 4：webSDK
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("source")]
            public int Source { get; init; }

            	
            /// <summary>
            /// 用户填写的联系方式
            /// 字段权限要求（满足任一）：
            /// 获取用户邮箱信息仅自建应用
            /// 获取用户手机号仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("contact")]
            public string Contact { get; init; }

            	
            /// <summary>
            /// 反馈详情
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("description")]
            public string Description { get; init; }

            	
            /// <summary>
            /// 反馈图片url列表，url 过期时间三天
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("images")]
            public string[] Images { get; init; }

            	
            /// <summary>
            /// 应用反馈 ID，应用反馈记录唯一标识
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("feedback_id")]
            public string FeedbackId { get; init; }

            	
            /// <summary>
            /// 反馈页面路径
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("feedback_path")]
            public string FeedbackPath { get; init; }
        }

        // user_id|union_id:string||user_id:string||open_id:string|
        public class UserId
        {
            	
            /// <summary>
            /// 用户的 union id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// 用户的 user id
            /// 字段权限要求：
            /// 获取用户 user ID仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserIdValue { get; init; }

            	
            /// <summary>
            /// 用户的 open id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }
    }
}