// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace  FeishuNetSdk.FeishuEvent.V2.Application.Application.Feedback
{
    /// <summary>
    /// 反馈更新<br/>
    /// 当反馈的处理状态被更新时，触发该事件<br/>
    /// </summary>
    /// <事件类型> application.application.feedback.updated_v6 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/application-v6/application-feedback/events/updated">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 管理应用反馈数据 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// <ul>
    /// <li> 获取用户 user ID (仅自建应用) </li>
    /// </ul>
    /// </字段权限要求>
    public class UpdatedV6 : EventContext<UpdatedV6.EventData>
    {
        // EventData|feedback_ids:string||status:int||app_id:string||update_time:string||operator_id:user_id|union_id:string||user_id:string||open_id:string|
        public class EventData
        {
            	
            /// <summary>
            /// 反馈id列表
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("feedback_ids")]
            public string[] FeedbackIds { get; init; }

            	
            /// <summary>
            /// 反馈处理状态（枚举值，0: 未处理  1: 已处理  2: 处理中 3: 已关闭）
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("status")]
            public int Status { get; init; }

            	
            /// <summary>
            /// 应用的 app_id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("app_id")]
            public string AppId { get; init; }

            	
            /// <summary>
            /// 反馈处理时间，格式为yyyy-mm-dd hh:mm:ss
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("update_time")]
            public string UpdateTime { get; init; }

            	
            /// <summary>
            /// 操作者用户 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("operator_id")]
            public UserId OperatorId { get; init; }
        }

        // user_id|union_id:string||user_id:string||open_id:string|
        public class UserId
        {
            	
            /// <summary>
            /// 用户的 union id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// 用户的 user id
            /// 字段权限要求：
            /// 获取用户 user ID仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserIdValue { get; init; }

            	
            /// <summary>
            /// 用户的 open id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }
    }
}