// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Hire.EcoAccount
{
    /// <summary>
    /// 账号绑定<br/>
    /// 招聘管理员添加三方服务商帐号时，系统会推送事件给应用开发者，开发者可根据事件获取用户添加的帐号类型（背调 或 笔试）和 帐号自定义字段信息，并根据这些信息识别用户在服务商处的身份，完成三方服务商帐号 和 招聘帐号之间的绑定，并根据用户服务商身份推送对应的背调套餐或试卷列表。<br/>
    /// </summary>
    /// <事件类型> hire.eco_account.created_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/ukTMukTMukTM/uMzM1YjLzMTN24yMzUjN/hire-v1/eco_account/events/created">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取招聘背调信息 </li>
    /// <li> 获取笔试信息 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class CreatedV1 : EventContext<CreatedV1.EventData>
    {
        // EventData|scope:int||account_id:string||account_name:string||usage_list:int||custom_field_list:eco_account_custom_field_event_data|key:string||value:string|
        public class EventData
        {
            	
            /// <summary>
            /// 账号类型
            /// 可选值有：
            /// 1：背调账号2：笔试账号
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("scope")]
            public int Scope { get; init; }

            	
            /// <summary>
            /// 账号 ID，招聘系统内唯一
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("account_id")]
            public string AccountId { get; init; }

            	
            /// <summary>
            /// 账号名称
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("account_name")]
            public string AccountName { get; init; }

            	
            /// <summary>
            /// 账号适用范围，1-社招，2-校招
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("usage_list")]
            public int[] UsageList { get; init; }

            	
            /// <summary>
            /// 自定义字段键值对
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("custom_field_list")]
            public EcoAccountCustomFieldEventData[] CustomFieldList { get; init; }
        }

        // eco_account_custom_field_event_data|key:string||value:string|
        public class EcoAccountCustomFieldEventData
        {
            	
            /// <summary>
            /// 自定义字段的标识
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("key")]
            public string Key { get; init; }

            	
            /// <summary>
            /// 自定义字段的值
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("value")]
            public string Value { get; init; }
        }
    }
}