// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Task.Task
{
    /// <summary>
    /// 任务信息变更（应用维度）<br/>
    /// 当 APP 订阅此事件后可以接收到由该 APP 创建的任务发生的变更，包括任务标题、描述、截止时间、协作者、关注者、提醒时间、状态（完成或取消完成）。<br/>
    /// </summary>
    /// <事件类型> task.task.updated_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task/events/updated">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 查看、创建、编辑和删除任务 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class UpdatedV1 : EventContext<UpdatedV1.EventData>
    {
        // EventData|task_id:string||obj_type:int|
        public class EventData
        {
            	
            /// <summary>
            /// 任务ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("task_id")]
            public string TaskId { get; init; }

            	
            /// <summary>
            /// 通知类型（1：任务详情发生变化，2：任务协作者发生变化，3：任务关注者发生变化，4：任务提醒时间发生变化，5：任务完成，6：任务取消完成，7：任务删除）
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("obj_type")]
            public int ObjType { get; init; }
        }
    }
}