// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Task.Task
{
    /// <summary>
    /// 任务信息变更（租户维度）<br/>
    /// APP 订阅此事件后可接收到该 APP 所在租户的所有来源接口创建的任务的变更事件。事件体为发生变更任务的相关用户的 open_id，可用此 open_id ，通过 获取任务列表接口获取与该用户相关的所有任务。<br/>
    /// </summary>
    /// <事件类型> task.task.update_tenant_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task/events/update_tenant">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 租户维度下任务变更事件订阅 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// 无
    /// </字段权限要求>
    public class UpdateTenantV1 : EventContext<UpdateTenantV1.EventData>
    {
        // EventData|user_id_list:user_id_list|user_id_list:user_id|union_id:string||user_id:string||open_id:string||task_id:string||object_type:string||event_type:string|
        public class EventData
        {
            	
            /// <summary>
            /// 用户 ID 列表
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id_list")]
            public UserIdList UserIdList { get; init; }

            	
            /// <summary>
            /// 任务的id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("task_id")]
            public string TaskId { get; init; }

            	
            /// <summary>
            /// 变更的数据类型，可选值："task"，"collaborator"，"follower"
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("object_type")]
            public string ObjectType { get; init; }

            	
            /// <summary>
            /// 事件类型，可选值："create"，"delete"，"update"
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("event_type")]
            public string EventType { get; init; }
        }

        // user_id_list|user_id_list:user_id|union_id:string||user_id:string||open_id:string|
        public class UserIdList
        {
            	
            /// <summary>
            /// 用户 ID 列表
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id_list")]
            public UserId[] UserIdListValue { get; init; }
        }

        // user_id|union_id:string||user_id:string||open_id:string|
        public class UserId
        {
            	
            /// <summary>
            /// 忽略此字段
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// 忽略此字段
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserIdValue { get; init; }

            	
            /// <summary>
            /// 用户的 open_id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }
    }
}