// <auto-generated />


using FeishuNetSdk.FeishuEvent.V2;

namespace FeishuNetSdk.FeishuEvent.V2.Vc.Meeting
{
    /// <summary>
    /// 录制完成<br/>
    /// 发生在录制文件上传完毕时【仅通过Open API预约的会议会产生此类事件】<br/>
    /// </summary>
    /// <事件类型> vc.meeting.recording_ready_v1 </事件类型>
    /// <事件版本> V2.0 </事件版本>
    /// <自建应用> 支持 </自建应用>
    /// <商店应用> 支持 </商店应用>
    /// <文档链接> <a href="https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/meeting/events/recording_ready">在open.feishu.cn中查看</a> </文档链接>
    /// <权限要求>
    /// <ul>
    /// <li> 获取会议信息 </li>
    /// </ul>
    /// </权限要求>
    /// <字段权限要求>
    /// <ul>
    /// <li> 获取用户 user ID (仅自建应用) </li>
    /// </ul>
    /// </字段权限要求>
    public class RecordingReadyV1 : EventContext<RecordingReadyV1.EventData>
    {
        // EventData|meeting:meeting_event_meeting|id:string||topic:string||meeting_no:string||owner:meeting_event_user|id:user_id|union_id:string||user_id:string||open_id:string||url:string||duration:string|
        public class EventData
        {
            	
            /// <summary>
            /// 会议数据
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("meeting")]
            public MeetingEventMeeting Meeting { get; init; }

            	
            /// <summary>
            /// 会议录制链接
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("url")]
            public string Url { get; init; }

            	
            /// <summary>
            /// 录制总时长（单位msec）
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("duration")]
            public string Duration { get; init; }
        }

        // meeting_event_meeting|id:string||topic:string||meeting_no:string||owner:meeting_event_user|id:user_id|union_id:string||user_id:string||open_id:string|
        public class MeetingEventMeeting
        {
            	
            /// <summary>
            /// 会议ID（视频会议的唯一标识，视频会议开始后才会产生）
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("id")]
            public string Id { get; init; }

            	
            /// <summary>
            /// 会议主题
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("topic")]
            public string Topic { get; init; }

            	
            /// <summary>
            /// 9位会议号（飞书用户可通过输入9位会议号快捷入会）
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("meeting_no")]
            public string MeetingNo { get; init; }

            	
            /// <summary>
            /// 会议拥有者
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("owner")]
            public MeetingEventUser Owner { get; init; }
        }

        // meeting_event_user|id:user_id|union_id:string||user_id:string||open_id:string|
        public class MeetingEventUser
        {
            	
            /// <summary>
            /// 用户 ID
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("id")]
            public UserId Id { get; init; }
        }

        // user_id|union_id:string||user_id:string||open_id:string|
        public class UserId
        {
            	
            /// <summary>
            /// 用户的 union id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("union_id")]
            public string UnionId { get; init; }

            	
            /// <summary>
            /// 用户的 user id
            /// 字段权限要求：
            /// 获取用户 user ID仅自建应用
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("user_id")]
            public string UserIdValue { get; init; }

            	
            /// <summary>
            /// 用户的 open id
            /// </summary>
            [global::System.Text.Json.Serialization.JsonPropertyName("open_id")]
            public string OpenId { get; init; }
        }
    }
}